// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=../../mocks/mock_game.go -package=mocks GameRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/bmstu-itstech/tjudge/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockGameRepository is a mock of GameRepository interface.
type MockGameRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGameRepositoryMockRecorder
	isgomock struct{}
}

// MockGameRepositoryMockRecorder is the mock recorder for MockGameRepository.
type MockGameRepositoryMockRecorder struct {
	mock *MockGameRepository
}

// NewMockGameRepository creates a new mock instance.
func NewMockGameRepository(ctrl *gomock.Controller) *MockGameRepository {
	mock := &MockGameRepository{ctrl: ctrl}
	mock.recorder = &MockGameRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameRepository) EXPECT() *MockGameRepositoryMockRecorder {
	return m.recorder
}

// AddToTournament mocks base method.
func (m *MockGameRepository) AddToTournament(ctx context.Context, tournamentID, gameID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToTournament", ctx, tournamentID, gameID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddToTournament indicates an expected call of AddToTournament.
func (mr *MockGameRepositoryMockRecorder) AddToTournament(ctx, tournamentID, gameID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToTournament", reflect.TypeOf((*MockGameRepository)(nil).AddToTournament), ctx, tournamentID, gameID)
}

// Create mocks base method.
func (m *MockGameRepository) Create(ctx context.Context, game *domain.Game) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, game)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockGameRepositoryMockRecorder) Create(ctx, game any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGameRepository)(nil).Create), ctx, game)
}

// Delete mocks base method.
func (m *MockGameRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGameRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGameRepository)(nil).Delete), ctx, id)
}

// Exists mocks base method.
func (m *MockGameRepository) Exists(ctx context.Context, name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockGameRepositoryMockRecorder) Exists(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockGameRepository)(nil).Exists), ctx, name)
}

// GetByID mocks base method.
func (m *MockGameRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockGameRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockGameRepository)(nil).GetByID), ctx, id)
}

// GetByName mocks base method.
func (m *MockGameRepository) GetByName(ctx context.Context, name string) (*domain.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*domain.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockGameRepositoryMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockGameRepository)(nil).GetByName), ctx, name)
}

// GetByTournamentID mocks base method.
func (m *MockGameRepository) GetByTournamentID(ctx context.Context, tournamentID uuid.UUID) ([]*domain.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTournamentID", ctx, tournamentID)
	ret0, _ := ret[0].([]*domain.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTournamentID indicates an expected call of GetByTournamentID.
func (mr *MockGameRepositoryMockRecorder) GetByTournamentID(ctx, tournamentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTournamentID", reflect.TypeOf((*MockGameRepository)(nil).GetByTournamentID), ctx, tournamentID)
}

// List mocks base method.
func (m *MockGameRepository) List(ctx context.Context, filter domain.GameFilter) ([]*domain.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]*domain.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockGameRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGameRepository)(nil).List), ctx, filter)
}

// RemoveFromTournament mocks base method.
func (m *MockGameRepository) RemoveFromTournament(ctx context.Context, tournamentID, gameID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFromTournament", ctx, tournamentID, gameID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFromTournament indicates an expected call of RemoveFromTournament.
func (mr *MockGameRepositoryMockRecorder) RemoveFromTournament(ctx, tournamentID, gameID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFromTournament", reflect.TypeOf((*MockGameRepository)(nil).RemoveFromTournament), ctx, tournamentID, gameID)
}

// Update mocks base method.
func (m *MockGameRepository) Update(ctx context.Context, game *domain.Game) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, game)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockGameRepositoryMockRecorder) Update(ctx, game any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGameRepository)(nil).Update), ctx, game)
}
