// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bmstu-itstech/tjudge/internal/domain/tournament (interfaces: TournamentCacher,LeaderboardCacher,TournamentRepository,MatchRepository,QueueManager)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_tournament.go -package=mocks github.com/bmstu-itstech/tjudge/internal/domain/tournament TournamentCacher,LeaderboardCacher,TournamentRepository,MatchRepository,QueueManager
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/bmstu-itstech/tjudge/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTournamentCacher is a mock of TournamentCacher interface.
type MockTournamentCacher struct {
	ctrl     *gomock.Controller
	recorder *MockTournamentCacherMockRecorder
	isgomock struct{}
}

// MockTournamentCacherMockRecorder is the mock recorder for MockTournamentCacher.
type MockTournamentCacherMockRecorder struct {
	mock *MockTournamentCacher
}

// NewMockTournamentCacher creates a new mock instance.
func NewMockTournamentCacher(ctrl *gomock.Controller) *MockTournamentCacher {
	mock := &MockTournamentCacher{ctrl: ctrl}
	mock.recorder = &MockTournamentCacherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTournamentCacher) EXPECT() *MockTournamentCacherMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockTournamentCacher) Get(ctx context.Context, tournamentID uuid.UUID) (*domain.Tournament, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, tournamentID)
	ret0, _ := ret[0].(*domain.Tournament)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTournamentCacherMockRecorder) Get(ctx, tournamentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTournamentCacher)(nil).Get), ctx, tournamentID)
}

// Invalidate mocks base method.
func (m *MockTournamentCacher) Invalidate(ctx context.Context, tournamentID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Invalidate", ctx, tournamentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Invalidate indicates an expected call of Invalidate.
func (mr *MockTournamentCacherMockRecorder) Invalidate(ctx, tournamentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invalidate", reflect.TypeOf((*MockTournamentCacher)(nil).Invalidate), ctx, tournamentID)
}

// Set mocks base method.
func (m *MockTournamentCacher) Set(ctx context.Context, tournament *domain.Tournament) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, tournament)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockTournamentCacherMockRecorder) Set(ctx, tournament any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockTournamentCacher)(nil).Set), ctx, tournament)
}

// MockLeaderboardCacher is a mock of LeaderboardCacher interface.
type MockLeaderboardCacher struct {
	ctrl     *gomock.Controller
	recorder *MockLeaderboardCacherMockRecorder
	isgomock struct{}
}

// MockLeaderboardCacherMockRecorder is the mock recorder for MockLeaderboardCacher.
type MockLeaderboardCacherMockRecorder struct {
	mock *MockLeaderboardCacher
}

// NewMockLeaderboardCacher creates a new mock instance.
func NewMockLeaderboardCacher(ctrl *gomock.Controller) *MockLeaderboardCacher {
	mock := &MockLeaderboardCacher{ctrl: ctrl}
	mock.recorder = &MockLeaderboardCacherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLeaderboardCacher) EXPECT() *MockLeaderboardCacherMockRecorder {
	return m.recorder
}

// Clear mocks base method.
func (m *MockLeaderboardCacher) Clear(ctx context.Context, tournamentID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clear", ctx, tournamentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Clear indicates an expected call of Clear.
func (mr *MockLeaderboardCacherMockRecorder) Clear(ctx, tournamentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockLeaderboardCacher)(nil).Clear), ctx, tournamentID)
}

// GetFullCrossGameLeaderboard mocks base method.
func (m *MockLeaderboardCacher) GetFullCrossGameLeaderboard(ctx context.Context, tournamentID uuid.UUID) ([]*domain.CrossGameLeaderboardEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFullCrossGameLeaderboard", ctx, tournamentID)
	ret0, _ := ret[0].([]*domain.CrossGameLeaderboardEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFullCrossGameLeaderboard indicates an expected call of GetFullCrossGameLeaderboard.
func (mr *MockLeaderboardCacherMockRecorder) GetFullCrossGameLeaderboard(ctx, tournamentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFullCrossGameLeaderboard", reflect.TypeOf((*MockLeaderboardCacher)(nil).GetFullCrossGameLeaderboard), ctx, tournamentID)
}

// GetFullLeaderboard mocks base method.
func (m *MockLeaderboardCacher) GetFullLeaderboard(ctx context.Context, tournamentID uuid.UUID, limit int) ([]*domain.LeaderboardEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFullLeaderboard", ctx, tournamentID, limit)
	ret0, _ := ret[0].([]*domain.LeaderboardEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFullLeaderboard indicates an expected call of GetFullLeaderboard.
func (mr *MockLeaderboardCacherMockRecorder) GetFullLeaderboard(ctx, tournamentID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFullLeaderboard", reflect.TypeOf((*MockLeaderboardCacher)(nil).GetFullLeaderboard), ctx, tournamentID, limit)
}

// GetTop mocks base method.
func (m *MockLeaderboardCacher) GetTop(ctx context.Context, tournamentID uuid.UUID, limit int) ([]*domain.LeaderboardEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTop", ctx, tournamentID, limit)
	ret0, _ := ret[0].([]*domain.LeaderboardEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTop indicates an expected call of GetTop.
func (mr *MockLeaderboardCacherMockRecorder) GetTop(ctx, tournamentID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTop", reflect.TypeOf((*MockLeaderboardCacher)(nil).GetTop), ctx, tournamentID, limit)
}

// InvalidateFullLeaderboard mocks base method.
func (m *MockLeaderboardCacher) InvalidateFullLeaderboard(ctx context.Context, tournamentID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateFullLeaderboard", ctx, tournamentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateFullLeaderboard indicates an expected call of InvalidateFullLeaderboard.
func (mr *MockLeaderboardCacherMockRecorder) InvalidateFullLeaderboard(ctx, tournamentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateFullLeaderboard", reflect.TypeOf((*MockLeaderboardCacher)(nil).InvalidateFullLeaderboard), ctx, tournamentID)
}

// SetFullCrossGameLeaderboard mocks base method.
func (m *MockLeaderboardCacher) SetFullCrossGameLeaderboard(ctx context.Context, tournamentID uuid.UUID, entries []*domain.CrossGameLeaderboardEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFullCrossGameLeaderboard", ctx, tournamentID, entries)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFullCrossGameLeaderboard indicates an expected call of SetFullCrossGameLeaderboard.
func (mr *MockLeaderboardCacherMockRecorder) SetFullCrossGameLeaderboard(ctx, tournamentID, entries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFullCrossGameLeaderboard", reflect.TypeOf((*MockLeaderboardCacher)(nil).SetFullCrossGameLeaderboard), ctx, tournamentID, entries)
}

// SetFullLeaderboard mocks base method.
func (m *MockLeaderboardCacher) SetFullLeaderboard(ctx context.Context, tournamentID uuid.UUID, limit int, entries []*domain.LeaderboardEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFullLeaderboard", ctx, tournamentID, limit, entries)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFullLeaderboard indicates an expected call of SetFullLeaderboard.
func (mr *MockLeaderboardCacherMockRecorder) SetFullLeaderboard(ctx, tournamentID, limit, entries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFullLeaderboard", reflect.TypeOf((*MockLeaderboardCacher)(nil).SetFullLeaderboard), ctx, tournamentID, limit, entries)
}

// UpdateRating mocks base method.
func (m *MockLeaderboardCacher) UpdateRating(ctx context.Context, tournamentID, programID uuid.UUID, rating int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRating", ctx, tournamentID, programID, rating)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRating indicates an expected call of UpdateRating.
func (mr *MockLeaderboardCacherMockRecorder) UpdateRating(ctx, tournamentID, programID, rating any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRating", reflect.TypeOf((*MockLeaderboardCacher)(nil).UpdateRating), ctx, tournamentID, programID, rating)
}

// MockTournamentRepository is a mock of TournamentRepository interface.
type MockTournamentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTournamentRepositoryMockRecorder
	isgomock struct{}
}

// MockTournamentRepositoryMockRecorder is the mock recorder for MockTournamentRepository.
type MockTournamentRepositoryMockRecorder struct {
	mock *MockTournamentRepository
}

// NewMockTournamentRepository creates a new mock instance.
func NewMockTournamentRepository(ctrl *gomock.Controller) *MockTournamentRepository {
	mock := &MockTournamentRepository{ctrl: ctrl}
	mock.recorder = &MockTournamentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTournamentRepository) EXPECT() *MockTournamentRepositoryMockRecorder {
	return m.recorder
}

// AddParticipant mocks base method.
func (m *MockTournamentRepository) AddParticipant(ctx context.Context, participant *domain.TournamentParticipant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddParticipant", ctx, participant)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddParticipant indicates an expected call of AddParticipant.
func (mr *MockTournamentRepositoryMockRecorder) AddParticipant(ctx, participant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddParticipant", reflect.TypeOf((*MockTournamentRepository)(nil).AddParticipant), ctx, participant)
}

// Create mocks base method.
func (m *MockTournamentRepository) Create(ctx context.Context, tournament *domain.Tournament) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tournament)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTournamentRepositoryMockRecorder) Create(ctx, tournament any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTournamentRepository)(nil).Create), ctx, tournament)
}

// Delete mocks base method.
func (m *MockTournamentRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTournamentRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTournamentRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockTournamentRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Tournament, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Tournament)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTournamentRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTournamentRepository)(nil).GetByID), ctx, id)
}

// GetCrossGameLeaderboard mocks base method.
func (m *MockTournamentRepository) GetCrossGameLeaderboard(ctx context.Context, tournamentID uuid.UUID) ([]*domain.CrossGameLeaderboardEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCrossGameLeaderboard", ctx, tournamentID)
	ret0, _ := ret[0].([]*domain.CrossGameLeaderboardEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCrossGameLeaderboard indicates an expected call of GetCrossGameLeaderboard.
func (mr *MockTournamentRepositoryMockRecorder) GetCrossGameLeaderboard(ctx, tournamentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCrossGameLeaderboard", reflect.TypeOf((*MockTournamentRepository)(nil).GetCrossGameLeaderboard), ctx, tournamentID)
}

// GetLatestParticipants mocks base method.
func (m *MockTournamentRepository) GetLatestParticipants(ctx context.Context, tournamentID uuid.UUID) ([]*domain.TournamentParticipant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestParticipants", ctx, tournamentID)
	ret0, _ := ret[0].([]*domain.TournamentParticipant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestParticipants indicates an expected call of GetLatestParticipants.
func (mr *MockTournamentRepositoryMockRecorder) GetLatestParticipants(ctx, tournamentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestParticipants", reflect.TypeOf((*MockTournamentRepository)(nil).GetLatestParticipants), ctx, tournamentID)
}

// GetLatestParticipantsByGame mocks base method.
func (m *MockTournamentRepository) GetLatestParticipantsByGame(ctx context.Context, tournamentID uuid.UUID, gameType string) ([]*domain.TournamentParticipant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestParticipantsByGame", ctx, tournamentID, gameType)
	ret0, _ := ret[0].([]*domain.TournamentParticipant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestParticipantsByGame indicates an expected call of GetLatestParticipantsByGame.
func (mr *MockTournamentRepositoryMockRecorder) GetLatestParticipantsByGame(ctx, tournamentID, gameType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestParticipantsByGame", reflect.TypeOf((*MockTournamentRepository)(nil).GetLatestParticipantsByGame), ctx, tournamentID, gameType)
}

// GetLatestParticipantsGroupedByGame mocks base method.
func (m *MockTournamentRepository) GetLatestParticipantsGroupedByGame(ctx context.Context, tournamentID uuid.UUID) (map[string][]*domain.TournamentParticipant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestParticipantsGroupedByGame", ctx, tournamentID)
	ret0, _ := ret[0].(map[string][]*domain.TournamentParticipant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestParticipantsGroupedByGame indicates an expected call of GetLatestParticipantsGroupedByGame.
func (mr *MockTournamentRepositoryMockRecorder) GetLatestParticipantsGroupedByGame(ctx, tournamentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestParticipantsGroupedByGame", reflect.TypeOf((*MockTournamentRepository)(nil).GetLatestParticipantsGroupedByGame), ctx, tournamentID)
}

// GetLeaderboard mocks base method.
func (m *MockTournamentRepository) GetLeaderboard(ctx context.Context, tournamentID uuid.UUID, limit int) ([]*domain.LeaderboardEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLeaderboard", ctx, tournamentID, limit)
	ret0, _ := ret[0].([]*domain.LeaderboardEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLeaderboard indicates an expected call of GetLeaderboard.
func (mr *MockTournamentRepositoryMockRecorder) GetLeaderboard(ctx, tournamentID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLeaderboard", reflect.TypeOf((*MockTournamentRepository)(nil).GetLeaderboard), ctx, tournamentID, limit)
}

// GetParticipants mocks base method.
func (m *MockTournamentRepository) GetParticipants(ctx context.Context, tournamentID uuid.UUID) ([]*domain.TournamentParticipant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParticipants", ctx, tournamentID)
	ret0, _ := ret[0].([]*domain.TournamentParticipant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParticipants indicates an expected call of GetParticipants.
func (mr *MockTournamentRepositoryMockRecorder) GetParticipants(ctx, tournamentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParticipants", reflect.TypeOf((*MockTournamentRepository)(nil).GetParticipants), ctx, tournamentID)
}

// GetParticipantsCount mocks base method.
func (m *MockTournamentRepository) GetParticipantsCount(ctx context.Context, tournamentID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParticipantsCount", ctx, tournamentID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParticipantsCount indicates an expected call of GetParticipantsCount.
func (mr *MockTournamentRepositoryMockRecorder) GetParticipantsCount(ctx, tournamentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParticipantsCount", reflect.TypeOf((*MockTournamentRepository)(nil).GetParticipantsCount), ctx, tournamentID)
}

// GetTeamsCount mocks base method.
func (m *MockTournamentRepository) GetTeamsCount(ctx context.Context, tournamentID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamsCount", ctx, tournamentID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamsCount indicates an expected call of GetTeamsCount.
func (mr *MockTournamentRepositoryMockRecorder) GetTeamsCount(ctx, tournamentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamsCount", reflect.TypeOf((*MockTournamentRepository)(nil).GetTeamsCount), ctx, tournamentID)
}

// List mocks base method.
func (m *MockTournamentRepository) List(ctx context.Context, filter domain.TournamentFilter) ([]*domain.Tournament, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]*domain.Tournament)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTournamentRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTournamentRepository)(nil).List), ctx, filter)
}

// Update mocks base method.
func (m *MockTournamentRepository) Update(ctx context.Context, tournament *domain.Tournament) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, tournament)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTournamentRepositoryMockRecorder) Update(ctx, tournament any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTournamentRepository)(nil).Update), ctx, tournament)
}

// UpdateStatus mocks base method.
func (m *MockTournamentRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status domain.TournamentStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockTournamentRepositoryMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockTournamentRepository)(nil).UpdateStatus), ctx, id, status)
}

// MockMatchRepository is a mock of MatchRepository interface.
type MockMatchRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMatchRepositoryMockRecorder
	isgomock struct{}
}

// MockMatchRepositoryMockRecorder is the mock recorder for MockMatchRepository.
type MockMatchRepositoryMockRecorder struct {
	mock *MockMatchRepository
}

// NewMockMatchRepository creates a new mock instance.
func NewMockMatchRepository(ctrl *gomock.Controller) *MockMatchRepository {
	mock := &MockMatchRepository{ctrl: ctrl}
	mock.recorder = &MockMatchRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchRepository) EXPECT() *MockMatchRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMatchRepository) Create(ctx context.Context, match *domain.Match) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, match)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMatchRepositoryMockRecorder) Create(ctx, match any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMatchRepository)(nil).Create), ctx, match)
}

// CreateBatch mocks base method.
func (m *MockMatchRepository) CreateBatch(ctx context.Context, matches []*domain.Match) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", ctx, matches)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockMatchRepositoryMockRecorder) CreateBatch(ctx, matches any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockMatchRepository)(nil).CreateBatch), ctx, matches)
}

// GetByTournamentID mocks base method.
func (m *MockMatchRepository) GetByTournamentID(ctx context.Context, tournamentID uuid.UUID, limit, offset int) ([]*domain.Match, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTournamentID", ctx, tournamentID, limit, offset)
	ret0, _ := ret[0].([]*domain.Match)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTournamentID indicates an expected call of GetByTournamentID.
func (mr *MockMatchRepositoryMockRecorder) GetByTournamentID(ctx, tournamentID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTournamentID", reflect.TypeOf((*MockMatchRepository)(nil).GetByTournamentID), ctx, tournamentID, limit, offset)
}

// GetMatchesByRounds mocks base method.
func (m *MockMatchRepository) GetMatchesByRounds(ctx context.Context, tournamentID uuid.UUID) ([]*domain.MatchRound, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMatchesByRounds", ctx, tournamentID)
	ret0, _ := ret[0].([]*domain.MatchRound)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMatchesByRounds indicates an expected call of GetMatchesByRounds.
func (mr *MockMatchRepositoryMockRecorder) GetMatchesByRounds(ctx, tournamentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMatchesByRounds", reflect.TypeOf((*MockMatchRepository)(nil).GetMatchesByRounds), ctx, tournamentID)
}

// GetNextRoundNumber mocks base method.
func (m *MockMatchRepository) GetNextRoundNumber(ctx context.Context, tournamentID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextRoundNumber", ctx, tournamentID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNextRoundNumber indicates an expected call of GetNextRoundNumber.
func (mr *MockMatchRepositoryMockRecorder) GetNextRoundNumber(ctx, tournamentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextRoundNumber", reflect.TypeOf((*MockMatchRepository)(nil).GetNextRoundNumber), ctx, tournamentID)
}

// GetNextRoundNumberByGame mocks base method.
func (m *MockMatchRepository) GetNextRoundNumberByGame(ctx context.Context, tournamentID uuid.UUID, gameType string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextRoundNumberByGame", ctx, tournamentID, gameType)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNextRoundNumberByGame indicates an expected call of GetNextRoundNumberByGame.
func (mr *MockMatchRepositoryMockRecorder) GetNextRoundNumberByGame(ctx, tournamentID, gameType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextRoundNumberByGame", reflect.TypeOf((*MockMatchRepository)(nil).GetNextRoundNumberByGame), ctx, tournamentID, gameType)
}

// GetPendingByTournamentAndGame mocks base method.
func (m *MockMatchRepository) GetPendingByTournamentAndGame(ctx context.Context, tournamentID uuid.UUID, gameType string) ([]*domain.Match, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingByTournamentAndGame", ctx, tournamentID, gameType)
	ret0, _ := ret[0].([]*domain.Match)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingByTournamentAndGame indicates an expected call of GetPendingByTournamentAndGame.
func (mr *MockMatchRepositoryMockRecorder) GetPendingByTournamentAndGame(ctx, tournamentID, gameType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingByTournamentAndGame", reflect.TypeOf((*MockMatchRepository)(nil).GetPendingByTournamentAndGame), ctx, tournamentID, gameType)
}

// GetPendingByTournamentID mocks base method.
func (m *MockMatchRepository) GetPendingByTournamentID(ctx context.Context, tournamentID uuid.UUID) ([]*domain.Match, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingByTournamentID", ctx, tournamentID)
	ret0, _ := ret[0].([]*domain.Match)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingByTournamentID indicates an expected call of GetPendingByTournamentID.
func (mr *MockMatchRepositoryMockRecorder) GetPendingByTournamentID(ctx, tournamentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingByTournamentID", reflect.TypeOf((*MockMatchRepository)(nil).GetPendingByTournamentID), ctx, tournamentID)
}

// GetPlayedProgramPairs mocks base method.
func (m *MockMatchRepository) GetPlayedProgramPairs(ctx context.Context, tournamentID uuid.UUID, gameType string) (map[string]struct{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlayedProgramPairs", ctx, tournamentID, gameType)
	ret0, _ := ret[0].(map[string]struct{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlayedProgramPairs indicates an expected call of GetPlayedProgramPairs.
func (mr *MockMatchRepositoryMockRecorder) GetPlayedProgramPairs(ctx, tournamentID, gameType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlayedProgramPairs", reflect.TypeOf((*MockMatchRepository)(nil).GetPlayedProgramPairs), ctx, tournamentID, gameType)
}

// ResetFailedMatches mocks base method.
func (m *MockMatchRepository) ResetFailedMatches(ctx context.Context, tournamentID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetFailedMatches", ctx, tournamentID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResetFailedMatches indicates an expected call of ResetFailedMatches.
func (mr *MockMatchRepositoryMockRecorder) ResetFailedMatches(ctx, tournamentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetFailedMatches", reflect.TypeOf((*MockMatchRepository)(nil).ResetFailedMatches), ctx, tournamentID)
}

// MockQueueManager is a mock of QueueManager interface.
type MockQueueManager struct {
	ctrl     *gomock.Controller
	recorder *MockQueueManagerMockRecorder
	isgomock struct{}
}

// MockQueueManagerMockRecorder is the mock recorder for MockQueueManager.
type MockQueueManagerMockRecorder struct {
	mock *MockQueueManager
}

// NewMockQueueManager creates a new mock instance.
func NewMockQueueManager(ctrl *gomock.Controller) *MockQueueManager {
	mock := &MockQueueManager{ctrl: ctrl}
	mock.recorder = &MockQueueManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueManager) EXPECT() *MockQueueManagerMockRecorder {
	return m.recorder
}

// Enqueue mocks base method.
func (m *MockQueueManager) Enqueue(ctx context.Context, match *domain.Match) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", ctx, match)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockQueueManagerMockRecorder) Enqueue(ctx, match any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockQueueManager)(nil).Enqueue), ctx, match)
}

// EnqueueBatch mocks base method.
func (m *MockQueueManager) EnqueueBatch(ctx context.Context, matches []*domain.Match) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueBatch", ctx, matches)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueBatch indicates an expected call of EnqueueBatch.
func (mr *MockQueueManagerMockRecorder) EnqueueBatch(ctx, matches any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueBatch", reflect.TypeOf((*MockQueueManager)(nil).EnqueueBatch), ctx, matches)
}
