// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=../../mocks/mock_team.go -package=mocks TeamRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/bmstu-itstech/tjudge/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTeamRepository is a mock of TeamRepository interface.
type MockTeamRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTeamRepositoryMockRecorder
	isgomock struct{}
}

// MockTeamRepositoryMockRecorder is the mock recorder for MockTeamRepository.
type MockTeamRepositoryMockRecorder struct {
	mock *MockTeamRepository
}

// NewMockTeamRepository creates a new mock instance.
func NewMockTeamRepository(ctrl *gomock.Controller) *MockTeamRepository {
	mock := &MockTeamRepository{ctrl: ctrl}
	mock.recorder = &MockTeamRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamRepository) EXPECT() *MockTeamRepositoryMockRecorder {
	return m.recorder
}

// AddMember mocks base method.
func (m *MockTeamRepository) AddMember(ctx context.Context, member *domain.TeamMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", ctx, member)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMember indicates an expected call of AddMember.
func (mr *MockTeamRepositoryMockRecorder) AddMember(ctx, member any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockTeamRepository)(nil).AddMember), ctx, member)
}

// Create mocks base method.
func (m *MockTeamRepository) Create(ctx context.Context, team *domain.Team) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, team)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTeamRepositoryMockRecorder) Create(ctx, team any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTeamRepository)(nil).Create), ctx, team)
}

// Delete mocks base method.
func (m *MockTeamRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTeamRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTeamRepository)(nil).Delete), ctx, id)
}

// DisqualifyTeamFull mocks base method.
func (m *MockTeamRepository) DisqualifyTeamFull(ctx context.Context, teamID, tournamentID uuid.UUID) (int64, int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisqualifyTeamFull", ctx, teamID, tournamentID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(int64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// DisqualifyTeamFull indicates an expected call of DisqualifyTeamFull.
func (mr *MockTeamRepositoryMockRecorder) DisqualifyTeamFull(ctx, teamID, tournamentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisqualifyTeamFull", reflect.TypeOf((*MockTeamRepository)(nil).DisqualifyTeamFull), ctx, teamID, tournamentID)
}

// GenerateUniqueCode mocks base method.
func (m *MockTeamRepository) GenerateUniqueCode(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateUniqueCode", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateUniqueCode indicates an expected call of GenerateUniqueCode.
func (mr *MockTeamRepositoryMockRecorder) GenerateUniqueCode(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateUniqueCode", reflect.TypeOf((*MockTeamRepository)(nil).GenerateUniqueCode), ctx)
}

// GetByCode mocks base method.
func (m *MockTeamRepository) GetByCode(ctx context.Context, code string) (*domain.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(*domain.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockTeamRepositoryMockRecorder) GetByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockTeamRepository)(nil).GetByCode), ctx, code)
}

// GetByID mocks base method.
func (m *MockTeamRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTeamRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTeamRepository)(nil).GetByID), ctx, id)
}

// GetByTournamentID mocks base method.
func (m *MockTeamRepository) GetByTournamentID(ctx context.Context, tournamentID uuid.UUID) ([]*domain.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTournamentID", ctx, tournamentID)
	ret0, _ := ret[0].([]*domain.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTournamentID indicates an expected call of GetByTournamentID.
func (mr *MockTeamRepositoryMockRecorder) GetByTournamentID(ctx, tournamentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTournamentID", reflect.TypeOf((*MockTeamRepository)(nil).GetByTournamentID), ctx, tournamentID)
}

// GetMemberCount mocks base method.
func (m *MockTeamRepository) GetMemberCount(ctx context.Context, teamID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemberCount", ctx, teamID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMemberCount indicates an expected call of GetMemberCount.
func (mr *MockTeamRepositoryMockRecorder) GetMemberCount(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemberCount", reflect.TypeOf((*MockTeamRepository)(nil).GetMemberCount), ctx, teamID)
}

// GetMembers mocks base method.
func (m *MockTeamRepository) GetMembers(ctx context.Context, teamID uuid.UUID) ([]*domain.TeamMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembers", ctx, teamID)
	ret0, _ := ret[0].([]*domain.TeamMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembers indicates an expected call of GetMembers.
func (mr *MockTeamRepositoryMockRecorder) GetMembers(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembers", reflect.TypeOf((*MockTeamRepository)(nil).GetMembers), ctx, teamID)
}

// GetTeamWithMembers mocks base method.
func (m *MockTeamRepository) GetTeamWithMembers(ctx context.Context, teamID uuid.UUID) (*domain.TeamWithMembers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamWithMembers", ctx, teamID)
	ret0, _ := ret[0].(*domain.TeamWithMembers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamWithMembers indicates an expected call of GetTeamWithMembers.
func (mr *MockTeamRepositoryMockRecorder) GetTeamWithMembers(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamWithMembers", reflect.TypeOf((*MockTeamRepository)(nil).GetTeamWithMembers), ctx, teamID)
}

// GetUserTeamInTournament mocks base method.
func (m *MockTeamRepository) GetUserTeamInTournament(ctx context.Context, tournamentID, userID uuid.UUID) (*domain.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTeamInTournament", ctx, tournamentID, userID)
	ret0, _ := ret[0].(*domain.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserTeamInTournament indicates an expected call of GetUserTeamInTournament.
func (mr *MockTeamRepositoryMockRecorder) GetUserTeamInTournament(ctx, tournamentID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTeamInTournament", reflect.TypeOf((*MockTeamRepository)(nil).GetUserTeamInTournament), ctx, tournamentID, userID)
}

// IsTeamDisqualified mocks base method.
func (m *MockTeamRepository) IsTeamDisqualified(ctx context.Context, teamID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTeamDisqualified", ctx, teamID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTeamDisqualified indicates an expected call of IsTeamDisqualified.
func (mr *MockTeamRepositoryMockRecorder) IsTeamDisqualified(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTeamDisqualified", reflect.TypeOf((*MockTeamRepository)(nil).IsTeamDisqualified), ctx, teamID)
}

// IsUserInAnyTeamInTournament mocks base method.
func (m *MockTeamRepository) IsUserInAnyTeamInTournament(ctx context.Context, tournamentID, userID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserInAnyTeamInTournament", ctx, tournamentID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUserInAnyTeamInTournament indicates an expected call of IsUserInAnyTeamInTournament.
func (mr *MockTeamRepositoryMockRecorder) IsUserInAnyTeamInTournament(ctx, tournamentID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserInAnyTeamInTournament", reflect.TypeOf((*MockTeamRepository)(nil).IsUserInAnyTeamInTournament), ctx, tournamentID, userID)
}

// IsUserInTeam mocks base method.
func (m *MockTeamRepository) IsUserInTeam(ctx context.Context, teamID, userID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserInTeam", ctx, teamID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUserInTeam indicates an expected call of IsUserInTeam.
func (mr *MockTeamRepositoryMockRecorder) IsUserInTeam(ctx, teamID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserInTeam", reflect.TypeOf((*MockTeamRepository)(nil).IsUserInTeam), ctx, teamID, userID)
}

// List mocks base method.
func (m *MockTeamRepository) List(ctx context.Context, filter domain.TeamFilter) ([]*domain.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]*domain.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTeamRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTeamRepository)(nil).List), ctx, filter)
}

// RemoveMember mocks base method.
func (m *MockTeamRepository) RemoveMember(ctx context.Context, teamID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, teamID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockTeamRepositoryMockRecorder) RemoveMember(ctx, teamID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockTeamRepository)(nil).RemoveMember), ctx, teamID, userID)
}

// RestoreTeam mocks base method.
func (m *MockTeamRepository) RestoreTeam(ctx context.Context, teamID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreTeam", ctx, teamID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestoreTeam indicates an expected call of RestoreTeam.
func (mr *MockTeamRepositoryMockRecorder) RestoreTeam(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreTeam", reflect.TypeOf((*MockTeamRepository)(nil).RestoreTeam), ctx, teamID)
}

// Update mocks base method.
func (m *MockTeamRepository) Update(ctx context.Context, team *domain.Team) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, team)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTeamRepositoryMockRecorder) Update(ctx, team any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTeamRepository)(nil).Update), ctx, team)
}

// MockTournamentRepository is a mock of TournamentRepository interface.
type MockTournamentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTournamentRepositoryMockRecorder
	isgomock struct{}
}

// MockTournamentRepositoryMockRecorder is the mock recorder for MockTournamentRepository.
type MockTournamentRepositoryMockRecorder struct {
	mock *MockTournamentRepository
}

// NewMockTournamentRepository creates a new mock instance.
func NewMockTournamentRepository(ctrl *gomock.Controller) *MockTournamentRepository {
	mock := &MockTournamentRepository{ctrl: ctrl}
	mock.recorder = &MockTournamentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTournamentRepository) EXPECT() *MockTournamentRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockTournamentRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Tournament, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Tournament)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTournamentRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTournamentRepository)(nil).GetByID), ctx, id)
}

// MockDistributedLock is a mock of DistributedLock interface.
type MockDistributedLock struct {
	ctrl     *gomock.Controller
	recorder *MockDistributedLockMockRecorder
	isgomock struct{}
}

// MockDistributedLockMockRecorder is the mock recorder for MockDistributedLock.
type MockDistributedLockMockRecorder struct {
	mock *MockDistributedLock
}

// NewMockDistributedLock creates a new mock instance.
func NewMockDistributedLock(ctrl *gomock.Controller) *MockDistributedLock {
	mock := &MockDistributedLock{ctrl: ctrl}
	mock.recorder = &MockDistributedLockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDistributedLock) EXPECT() *MockDistributedLockMockRecorder {
	return m.recorder
}

// WithLock mocks base method.
func (m *MockDistributedLock) WithLock(ctx context.Context, key string, ttl time.Duration, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithLock", ctx, key, ttl, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithLock indicates an expected call of WithLock.
func (mr *MockDistributedLockMockRecorder) WithLock(ctx, key, ttl, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithLock", reflect.TypeOf((*MockDistributedLock)(nil).WithLock), ctx, key, ttl, fn)
}
