// Code generated by mockery v2.53.6. DO NOT EDIT.

package contractmocks

import (
	context "context"

	domain "github.com/bmstu-itstech/tjudge/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockGameProgramRepository is an autogenerated mock type for the GameProgramRepository type
type MockGameProgramRepository struct {
	mock.Mock
}

type MockGameProgramRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGameProgramRepository) EXPECT() *MockGameProgramRepository_Expecter {
	return &MockGameProgramRepository_Expecter{mock: &_m.Mock}
}

// GetByTournamentAndGame provides a mock function with given fields: ctx, tournamentID, gameID
func (_m *MockGameProgramRepository) GetByTournamentAndGame(ctx context.Context, tournamentID uuid.UUID, gameID uuid.UUID) ([]*domain.Program, error) {
	ret := _m.Called(ctx, tournamentID, gameID)

	if len(ret) == 0 {
		panic("no return value specified for GetByTournamentAndGame")
	}

	var r0 []*domain.Program
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]*domain.Program, error)); ok {
		return rf(ctx, tournamentID, gameID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []*domain.Program); ok {
		r0 = rf(ctx, tournamentID, gameID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Program)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tournamentID, gameID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGameProgramRepository_GetByTournamentAndGame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTournamentAndGame'
type MockGameProgramRepository_GetByTournamentAndGame_Call struct {
	*mock.Call
}

// GetByTournamentAndGame is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
//   - gameID uuid.UUID
func (_e *MockGameProgramRepository_Expecter) GetByTournamentAndGame(ctx interface{}, tournamentID interface{}, gameID interface{}) *MockGameProgramRepository_GetByTournamentAndGame_Call {
	return &MockGameProgramRepository_GetByTournamentAndGame_Call{Call: _e.mock.On("GetByTournamentAndGame", ctx, tournamentID, gameID)}
}

func (_c *MockGameProgramRepository_GetByTournamentAndGame_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID, gameID uuid.UUID)) *MockGameProgramRepository_GetByTournamentAndGame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockGameProgramRepository_GetByTournamentAndGame_Call) Return(_a0 []*domain.Program, _a1 error) *MockGameProgramRepository_GetByTournamentAndGame_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGameProgramRepository_GetByTournamentAndGame_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]*domain.Program, error)) *MockGameProgramRepository_GetByTournamentAndGame_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGameProgramRepository creates a new instance of MockGameProgramRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGameProgramRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGameProgramRepository {
	mock := &MockGameProgramRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
