// Code generated by mockery v2.53.6. DO NOT EDIT.

package contractmocks

import (
	context "context"

	domain "github.com/bmstu-itstech/tjudge/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockTournamentParticipantAdder is an autogenerated mock type for the TournamentParticipantAdder type
type MockTournamentParticipantAdder struct {
	mock.Mock
}

type MockTournamentParticipantAdder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTournamentParticipantAdder) EXPECT() *MockTournamentParticipantAdder_Expecter {
	return &MockTournamentParticipantAdder_Expecter{mock: &_m.Mock}
}

// AddParticipant provides a mock function with given fields: ctx, participant
func (_m *MockTournamentParticipantAdder) AddParticipant(ctx context.Context, participant *domain.TournamentParticipant) error {
	ret := _m.Called(ctx, participant)

	if len(ret) == 0 {
		panic("no return value specified for AddParticipant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.TournamentParticipant) error); ok {
		r0 = rf(ctx, participant)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTournamentParticipantAdder_AddParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddParticipant'
type MockTournamentParticipantAdder_AddParticipant_Call struct {
	*mock.Call
}

// AddParticipant is a helper method to define mock.On call
//   - ctx context.Context
//   - participant *domain.TournamentParticipant
func (_e *MockTournamentParticipantAdder_Expecter) AddParticipant(ctx interface{}, participant interface{}) *MockTournamentParticipantAdder_AddParticipant_Call {
	return &MockTournamentParticipantAdder_AddParticipant_Call{Call: _e.mock.On("AddParticipant", ctx, participant)}
}

func (_c *MockTournamentParticipantAdder_AddParticipant_Call) Run(run func(ctx context.Context, participant *domain.TournamentParticipant)) *MockTournamentParticipantAdder_AddParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.TournamentParticipant))
	})
	return _c
}

func (_c *MockTournamentParticipantAdder_AddParticipant_Call) Return(_a0 error) *MockTournamentParticipantAdder_AddParticipant_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTournamentParticipantAdder_AddParticipant_Call) RunAndReturn(run func(context.Context, *domain.TournamentParticipant) error) *MockTournamentParticipantAdder_AddParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTournamentParticipantAdder creates a new instance of MockTournamentParticipantAdder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTournamentParticipantAdder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTournamentParticipantAdder {
	mock := &MockTournamentParticipantAdder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
