// Code generated by mockery v2.53.6. DO NOT EDIT.

package contractmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRoundCompletionChecker is an autogenerated mock type for the RoundCompletionChecker type
type MockRoundCompletionChecker struct {
	mock.Mock
}

type MockRoundCompletionChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoundCompletionChecker) EXPECT() *MockRoundCompletionChecker_Expecter {
	return &MockRoundCompletionChecker_Expecter{mock: &_m.Mock}
}

// IsRoundCompleted provides a mock function with given fields: ctx, tournamentID, gameID
func (_m *MockRoundCompletionChecker) IsRoundCompleted(ctx context.Context, tournamentID uuid.UUID, gameID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, tournamentID, gameID)

	if len(ret) == 0 {
		panic("no return value specified for IsRoundCompleted")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(ctx, tournamentID, gameID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, tournamentID, gameID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tournamentID, gameID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoundCompletionChecker_IsRoundCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRoundCompleted'
type MockRoundCompletionChecker_IsRoundCompleted_Call struct {
	*mock.Call
}

// IsRoundCompleted is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
//   - gameID uuid.UUID
func (_e *MockRoundCompletionChecker_Expecter) IsRoundCompleted(ctx interface{}, tournamentID interface{}, gameID interface{}) *MockRoundCompletionChecker_IsRoundCompleted_Call {
	return &MockRoundCompletionChecker_IsRoundCompleted_Call{Call: _e.mock.On("IsRoundCompleted", ctx, tournamentID, gameID)}
}

func (_c *MockRoundCompletionChecker_IsRoundCompleted_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID, gameID uuid.UUID)) *MockRoundCompletionChecker_IsRoundCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockRoundCompletionChecker_IsRoundCompleted_Call) Return(_a0 bool, _a1 error) *MockRoundCompletionChecker_IsRoundCompleted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoundCompletionChecker_IsRoundCompleted_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (bool, error)) *MockRoundCompletionChecker_IsRoundCompleted_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoundCompletionChecker creates a new instance of MockRoundCompletionChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoundCompletionChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoundCompletionChecker {
	mock := &MockRoundCompletionChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
