// Code generated by mockery v2.53.6. DO NOT EDIT.

package contractmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	queue "github.com/bmstu-itstech/tjudge/internal/infrastructure/queue"
)

// MockMatchQueueManager is an autogenerated mock type for the MatchQueueManager type
type MockMatchQueueManager struct {
	mock.Mock
}

type MockMatchQueueManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMatchQueueManager) EXPECT() *MockMatchQueueManager_Expecter {
	return &MockMatchQueueManager_Expecter{mock: &_m.Mock}
}

// Clear provides a mock function with given fields: ctx
func (_m *MockMatchQueueManager) Clear(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Clear")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMatchQueueManager_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type MockMatchQueueManager_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMatchQueueManager_Expecter) Clear(ctx interface{}) *MockMatchQueueManager_Clear_Call {
	return &MockMatchQueueManager_Clear_Call{Call: _e.mock.On("Clear", ctx)}
}

func (_c *MockMatchQueueManager_Clear_Call) Run(run func(ctx context.Context)) *MockMatchQueueManager_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMatchQueueManager_Clear_Call) Return(_a0 error) *MockMatchQueueManager_Clear_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMatchQueueManager_Clear_Call) RunAndReturn(run func(context.Context) error) *MockMatchQueueManager_Clear_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function with given fields: ctx
func (_m *MockMatchQueueManager) GetStats(ctx context.Context) (*queue.QueueStats, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 *queue.QueueStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*queue.QueueStats, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *queue.QueueStats); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*queue.QueueStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMatchQueueManager_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockMatchQueueManager_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMatchQueueManager_Expecter) GetStats(ctx interface{}) *MockMatchQueueManager_GetStats_Call {
	return &MockMatchQueueManager_GetStats_Call{Call: _e.mock.On("GetStats", ctx)}
}

func (_c *MockMatchQueueManager_GetStats_Call) Run(run func(ctx context.Context)) *MockMatchQueueManager_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMatchQueueManager_GetStats_Call) Return(_a0 *queue.QueueStats, _a1 error) *MockMatchQueueManager_GetStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMatchQueueManager_GetStats_Call) RunAndReturn(run func(context.Context) (*queue.QueueStats, error)) *MockMatchQueueManager_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeInvalidMatches provides a mock function with given fields: ctx, validator
func (_m *MockMatchQueueManager) PurgeInvalidMatches(ctx context.Context, validator func(string) bool) (int64, error) {
	ret := _m.Called(ctx, validator)

	if len(ret) == 0 {
		panic("no return value specified for PurgeInvalidMatches")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, func(string) bool) (int64, error)); ok {
		return rf(ctx, validator)
	}
	if rf, ok := ret.Get(0).(func(context.Context, func(string) bool) int64); ok {
		r0 = rf(ctx, validator)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, func(string) bool) error); ok {
		r1 = rf(ctx, validator)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMatchQueueManager_PurgeInvalidMatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeInvalidMatches'
type MockMatchQueueManager_PurgeInvalidMatches_Call struct {
	*mock.Call
}

// PurgeInvalidMatches is a helper method to define mock.On call
//   - ctx context.Context
//   - validator func(string) bool
func (_e *MockMatchQueueManager_Expecter) PurgeInvalidMatches(ctx interface{}, validator interface{}) *MockMatchQueueManager_PurgeInvalidMatches_Call {
	return &MockMatchQueueManager_PurgeInvalidMatches_Call{Call: _e.mock.On("PurgeInvalidMatches", ctx, validator)}
}

func (_c *MockMatchQueueManager_PurgeInvalidMatches_Call) Run(run func(ctx context.Context, validator func(string) bool)) *MockMatchQueueManager_PurgeInvalidMatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(string) bool))
	})
	return _c
}

func (_c *MockMatchQueueManager_PurgeInvalidMatches_Call) Return(_a0 int64, _a1 error) *MockMatchQueueManager_PurgeInvalidMatches_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMatchQueueManager_PurgeInvalidMatches_Call) RunAndReturn(run func(context.Context, func(string) bool) (int64, error)) *MockMatchQueueManager_PurgeInvalidMatches_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMatchQueueManager creates a new instance of MockMatchQueueManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMatchQueueManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMatchQueueManager {
	mock := &MockMatchQueueManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
