// Code generated by mockery v2.53.6. DO NOT EDIT.

package contractmocks

import (
	context "context"

	auth "github.com/bmstu-itstech/tjudge/internal/domain/auth"

	domain "github.com/bmstu-itstech/tjudge/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// GetUserFromToken provides a mock function with given fields: ctx, token
func (_m *MockAuthService) GetUserFromToken(ctx context.Context, token string) (*domain.User, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetUserFromToken")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_GetUserFromToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserFromToken'
type MockAuthService_GetUserFromToken_Call struct {
	*mock.Call
}

// GetUserFromToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockAuthService_Expecter) GetUserFromToken(ctx interface{}, token interface{}) *MockAuthService_GetUserFromToken_Call {
	return &MockAuthService_GetUserFromToken_Call{Call: _e.mock.On("GetUserFromToken", ctx, token)}
}

func (_c *MockAuthService_GetUserFromToken_Call) Run(run func(ctx context.Context, token string)) *MockAuthService_GetUserFromToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthService_GetUserFromToken_Call) Return(_a0 *domain.User, _a1 error) *MockAuthService_GetUserFromToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_GetUserFromToken_Call) RunAndReturn(run func(context.Context, string) (*domain.User, error)) *MockAuthService_GetUserFromToken_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, req
func (_m *MockAuthService) Login(ctx context.Context, req *auth.LoginRequest) (*auth.AuthResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *auth.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *auth.LoginRequest) (*auth.AuthResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *auth.LoginRequest) *auth.AuthResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *auth.LoginRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - req *auth.LoginRequest
func (_e *MockAuthService_Expecter) Login(ctx interface{}, req interface{}) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", ctx, req)}
}

func (_c *MockAuthService_Login_Call) Run(run func(ctx context.Context, req *auth.LoginRequest)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*auth.LoginRequest))
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(_a0 *auth.AuthResponse, _a1 error) *MockAuthService_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(context.Context, *auth.LoginRequest) (*auth.AuthResponse, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, accessToken, refreshToken
func (_m *MockAuthService) Logout(ctx context.Context, accessToken string, refreshToken string) error {
	ret := _m.Called(ctx, accessToken, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, accessToken, refreshToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - refreshToken string
func (_e *MockAuthService_Expecter) Logout(ctx interface{}, accessToken interface{}, refreshToken interface{}) *MockAuthService_Logout_Call {
	return &MockAuthService_Logout_Call{Call: _e.mock.On("Logout", ctx, accessToken, refreshToken)}
}

func (_c *MockAuthService_Logout_Call) Run(run func(ctx context.Context, accessToken string, refreshToken string)) *MockAuthService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAuthService_Logout_Call) Return(_a0 error) *MockAuthService_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthService_Logout_Call) RunAndReturn(run func(context.Context, string, string) error) *MockAuthService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshTokens provides a mock function with given fields: ctx, refreshToken
func (_m *MockAuthService) RefreshTokens(ctx context.Context, refreshToken string) (*auth.AuthResponse, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshTokens")
	}

	var r0 *auth.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*auth.AuthResponse, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *auth.AuthResponse); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_RefreshTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshTokens'
type MockAuthService_RefreshTokens_Call struct {
	*mock.Call
}

// RefreshTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockAuthService_Expecter) RefreshTokens(ctx interface{}, refreshToken interface{}) *MockAuthService_RefreshTokens_Call {
	return &MockAuthService_RefreshTokens_Call{Call: _e.mock.On("RefreshTokens", ctx, refreshToken)}
}

func (_c *MockAuthService_RefreshTokens_Call) Run(run func(ctx context.Context, refreshToken string)) *MockAuthService_RefreshTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthService_RefreshTokens_Call) Return(_a0 *auth.AuthResponse, _a1 error) *MockAuthService_RefreshTokens_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_RefreshTokens_Call) RunAndReturn(run func(context.Context, string) (*auth.AuthResponse, error)) *MockAuthService_RefreshTokens_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, req
func (_m *MockAuthService) Register(ctx context.Context, req *auth.RegisterRequest) (*auth.AuthResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *auth.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *auth.RegisterRequest) (*auth.AuthResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *auth.RegisterRequest) *auth.AuthResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *auth.RegisterRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - req *auth.RegisterRequest
func (_e *MockAuthService_Expecter) Register(ctx interface{}, req interface{}) *MockAuthService_Register_Call {
	return &MockAuthService_Register_Call{Call: _e.mock.On("Register", ctx, req)}
}

func (_c *MockAuthService_Register_Call) Run(run func(ctx context.Context, req *auth.RegisterRequest)) *MockAuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*auth.RegisterRequest))
	})
	return _c
}

func (_c *MockAuthService_Register_Call) Return(_a0 *auth.AuthResponse, _a1 error) *MockAuthService_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_Register_Call) RunAndReturn(run func(context.Context, *auth.RegisterRequest) (*auth.AuthResponse, error)) *MockAuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function with given fields: ctx, userID, req
func (_m *MockAuthService) UpdateProfile(ctx context.Context, userID string, req *auth.UpdateProfileRequest) (*domain.User, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *auth.UpdateProfileRequest) (*domain.User, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *auth.UpdateProfileRequest) *domain.User); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *auth.UpdateProfileRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type MockAuthService_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - req *auth.UpdateProfileRequest
func (_e *MockAuthService_Expecter) UpdateProfile(ctx interface{}, userID interface{}, req interface{}) *MockAuthService_UpdateProfile_Call {
	return &MockAuthService_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, userID, req)}
}

func (_c *MockAuthService_UpdateProfile_Call) Run(run func(ctx context.Context, userID string, req *auth.UpdateProfileRequest)) *MockAuthService_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*auth.UpdateProfileRequest))
	})
	return _c
}

func (_c *MockAuthService_UpdateProfile_Call) Return(_a0 *domain.User, _a1 error) *MockAuthService_UpdateProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_UpdateProfile_Call) RunAndReturn(run func(context.Context, string, *auth.UpdateProfileRequest) (*domain.User, error)) *MockAuthService_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function with given fields: token
func (_m *MockAuthService) ValidateToken(token string) (*auth.Claims, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *auth.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*auth.Claims, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *auth.Claims); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockAuthService_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - token string
func (_e *MockAuthService_Expecter) ValidateToken(token interface{}) *MockAuthService_ValidateToken_Call {
	return &MockAuthService_ValidateToken_Call{Call: _e.mock.On("ValidateToken", token)}
}

func (_c *MockAuthService_ValidateToken_Call) Run(run func(token string)) *MockAuthService_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAuthService_ValidateToken_Call) Return(_a0 *auth.Claims, _a1 error) *MockAuthService_ValidateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_ValidateToken_Call) RunAndReturn(run func(string) (*auth.Claims, error)) *MockAuthService_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
