// Code generated by mockery v2.53.6. DO NOT EDIT.

package contractmocks

import (
	context "context"

	domain "github.com/bmstu-itstech/tjudge/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockProgramRepository is an autogenerated mock type for the ProgramRepository type
type MockProgramRepository struct {
	mock.Mock
}

type MockProgramRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProgramRepository) EXPECT() *MockProgramRepository_Expecter {
	return &MockProgramRepository_Expecter{mock: &_m.Mock}
}

// CheckOwnership provides a mock function with given fields: ctx, programID, userID
func (_m *MockProgramRepository) CheckOwnership(ctx context.Context, programID uuid.UUID, userID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, programID, userID)

	if len(ret) == 0 {
		panic("no return value specified for CheckOwnership")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(ctx, programID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, programID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, programID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProgramRepository_CheckOwnership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckOwnership'
type MockProgramRepository_CheckOwnership_Call struct {
	*mock.Call
}

// CheckOwnership is a helper method to define mock.On call
//   - ctx context.Context
//   - programID uuid.UUID
//   - userID uuid.UUID
func (_e *MockProgramRepository_Expecter) CheckOwnership(ctx interface{}, programID interface{}, userID interface{}) *MockProgramRepository_CheckOwnership_Call {
	return &MockProgramRepository_CheckOwnership_Call{Call: _e.mock.On("CheckOwnership", ctx, programID, userID)}
}

func (_c *MockProgramRepository_CheckOwnership_Call) Run(run func(ctx context.Context, programID uuid.UUID, userID uuid.UUID)) *MockProgramRepository_CheckOwnership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockProgramRepository_CheckOwnership_Call) Return(_a0 bool, _a1 error) *MockProgramRepository_CheckOwnership_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProgramRepository_CheckOwnership_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (bool, error)) *MockProgramRepository_CheckOwnership_Call {
	_c.Call.Return(run)
	return _c
}

// ClearErrorMessages provides a mock function with given fields: ctx, tournamentID
func (_m *MockProgramRepository) ClearErrorMessages(ctx context.Context, tournamentID uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, tournamentID)

	if len(ret) == 0 {
		panic("no return value specified for ClearErrorMessages")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return rf(ctx, tournamentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = rf(ctx, tournamentID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tournamentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProgramRepository_ClearErrorMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearErrorMessages'
type MockProgramRepository_ClearErrorMessages_Call struct {
	*mock.Call
}

// ClearErrorMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
func (_e *MockProgramRepository_Expecter) ClearErrorMessages(ctx interface{}, tournamentID interface{}) *MockProgramRepository_ClearErrorMessages_Call {
	return &MockProgramRepository_ClearErrorMessages_Call{Call: _e.mock.On("ClearErrorMessages", ctx, tournamentID)}
}

func (_c *MockProgramRepository_ClearErrorMessages_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID)) *MockProgramRepository_ClearErrorMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockProgramRepository_ClearErrorMessages_Call) Return(_a0 int64, _a1 error) *MockProgramRepository_ClearErrorMessages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProgramRepository_ClearErrorMessages_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int64, error)) *MockProgramRepository_ClearErrorMessages_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, program
func (_m *MockProgramRepository) Create(ctx context.Context, program *domain.Program) error {
	ret := _m.Called(ctx, program)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Program) error); ok {
		r0 = rf(ctx, program)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProgramRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProgramRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - program *domain.Program
func (_e *MockProgramRepository_Expecter) Create(ctx interface{}, program interface{}) *MockProgramRepository_Create_Call {
	return &MockProgramRepository_Create_Call{Call: _e.mock.On("Create", ctx, program)}
}

func (_c *MockProgramRepository_Create_Call) Run(run func(ctx context.Context, program *domain.Program)) *MockProgramRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Program))
	})
	return _c
}

func (_c *MockProgramRepository_Create_Call) Return(_a0 error) *MockProgramRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProgramRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Program) error) *MockProgramRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithAtomicVersion provides a mock function with given fields: ctx, program
func (_m *MockProgramRepository) CreateWithAtomicVersion(ctx context.Context, program *domain.Program) error {
	ret := _m.Called(ctx, program)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithAtomicVersion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Program) error); ok {
		r0 = rf(ctx, program)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProgramRepository_CreateWithAtomicVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithAtomicVersion'
type MockProgramRepository_CreateWithAtomicVersion_Call struct {
	*mock.Call
}

// CreateWithAtomicVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - program *domain.Program
func (_e *MockProgramRepository_Expecter) CreateWithAtomicVersion(ctx interface{}, program interface{}) *MockProgramRepository_CreateWithAtomicVersion_Call {
	return &MockProgramRepository_CreateWithAtomicVersion_Call{Call: _e.mock.On("CreateWithAtomicVersion", ctx, program)}
}

func (_c *MockProgramRepository_CreateWithAtomicVersion_Call) Run(run func(ctx context.Context, program *domain.Program)) *MockProgramRepository_CreateWithAtomicVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Program))
	})
	return _c
}

func (_c *MockProgramRepository_CreateWithAtomicVersion_Call) Return(_a0 error) *MockProgramRepository_CreateWithAtomicVersion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProgramRepository_CreateWithAtomicVersion_Call) RunAndReturn(run func(context.Context, *domain.Program) error) *MockProgramRepository_CreateWithAtomicVersion_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockProgramRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProgramRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProgramRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockProgramRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockProgramRepository_Delete_Call {
	return &MockProgramRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockProgramRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockProgramRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockProgramRepository_Delete_Call) Return(_a0 error) *MockProgramRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProgramRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockProgramRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllVersionsByTeamAndGame provides a mock function with given fields: ctx, teamID, gameID
func (_m *MockProgramRepository) GetAllVersionsByTeamAndGame(ctx context.Context, teamID uuid.UUID, gameID uuid.UUID) ([]*domain.Program, error) {
	ret := _m.Called(ctx, teamID, gameID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllVersionsByTeamAndGame")
	}

	var r0 []*domain.Program
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]*domain.Program, error)); ok {
		return rf(ctx, teamID, gameID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []*domain.Program); ok {
		r0 = rf(ctx, teamID, gameID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Program)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, teamID, gameID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProgramRepository_GetAllVersionsByTeamAndGame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllVersionsByTeamAndGame'
type MockProgramRepository_GetAllVersionsByTeamAndGame_Call struct {
	*mock.Call
}

// GetAllVersionsByTeamAndGame is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
//   - gameID uuid.UUID
func (_e *MockProgramRepository_Expecter) GetAllVersionsByTeamAndGame(ctx interface{}, teamID interface{}, gameID interface{}) *MockProgramRepository_GetAllVersionsByTeamAndGame_Call {
	return &MockProgramRepository_GetAllVersionsByTeamAndGame_Call{Call: _e.mock.On("GetAllVersionsByTeamAndGame", ctx, teamID, gameID)}
}

func (_c *MockProgramRepository_GetAllVersionsByTeamAndGame_Call) Run(run func(ctx context.Context, teamID uuid.UUID, gameID uuid.UUID)) *MockProgramRepository_GetAllVersionsByTeamAndGame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockProgramRepository_GetAllVersionsByTeamAndGame_Call) Return(_a0 []*domain.Program, _a1 error) *MockProgramRepository_GetAllVersionsByTeamAndGame_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProgramRepository_GetAllVersionsByTeamAndGame_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]*domain.Program, error)) *MockProgramRepository_GetAllVersionsByTeamAndGame_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockProgramRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Program, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Program
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Program, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Program); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Program)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProgramRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockProgramRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockProgramRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockProgramRepository_GetByID_Call {
	return &MockProgramRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockProgramRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockProgramRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockProgramRepository_GetByID_Call) Return(_a0 *domain.Program, _a1 error) *MockProgramRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProgramRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Program, error)) *MockProgramRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *MockProgramRepository) GetByUserID(ctx context.Context, userID uuid.UUID) ([]*domain.Program, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*domain.Program
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*domain.Program, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.Program); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Program)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProgramRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockProgramRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockProgramRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *MockProgramRepository_GetByUserID_Call {
	return &MockProgramRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *MockProgramRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockProgramRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockProgramRepository_GetByUserID_Call) Return(_a0 []*domain.Program, _a1 error) *MockProgramRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProgramRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*domain.Program, error)) *MockProgramRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestVersion provides a mock function with given fields: ctx, teamID, gameID
func (_m *MockProgramRepository) GetLatestVersion(ctx context.Context, teamID uuid.UUID, gameID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, teamID, gameID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestVersion")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (int, error)); ok {
		return rf(ctx, teamID, gameID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) int); ok {
		r0 = rf(ctx, teamID, gameID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, teamID, gameID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProgramRepository_GetLatestVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestVersion'
type MockProgramRepository_GetLatestVersion_Call struct {
	*mock.Call
}

// GetLatestVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
//   - gameID uuid.UUID
func (_e *MockProgramRepository_Expecter) GetLatestVersion(ctx interface{}, teamID interface{}, gameID interface{}) *MockProgramRepository_GetLatestVersion_Call {
	return &MockProgramRepository_GetLatestVersion_Call{Call: _e.mock.On("GetLatestVersion", ctx, teamID, gameID)}
}

func (_c *MockProgramRepository_GetLatestVersion_Call) Run(run func(ctx context.Context, teamID uuid.UUID, gameID uuid.UUID)) *MockProgramRepository_GetLatestVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockProgramRepository_GetLatestVersion_Call) Return(_a0 int, _a1 error) *MockProgramRepository_GetLatestVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProgramRepository_GetLatestVersion_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (int, error)) *MockProgramRepository_GetLatestVersion_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, program
func (_m *MockProgramRepository) Update(ctx context.Context, program *domain.Program) error {
	ret := _m.Called(ctx, program)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Program) error); ok {
		r0 = rf(ctx, program)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProgramRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProgramRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - program *domain.Program
func (_e *MockProgramRepository_Expecter) Update(ctx interface{}, program interface{}) *MockProgramRepository_Update_Call {
	return &MockProgramRepository_Update_Call{Call: _e.mock.On("Update", ctx, program)}
}

func (_c *MockProgramRepository_Update_Call) Run(run func(ctx context.Context, program *domain.Program)) *MockProgramRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Program))
	})
	return _c
}

func (_c *MockProgramRepository_Update_Call) Return(_a0 error) *MockProgramRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProgramRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Program) error) *MockProgramRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProgramRepository creates a new instance of MockProgramRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProgramRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProgramRepository {
	mock := &MockProgramRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
