// Code generated by mockery v2.53.6. DO NOT EDIT.

package contractmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockSchedulingService is an autogenerated mock type for the SchedulingService type
type MockSchedulingService struct {
	mock.Mock
}

type MockSchedulingService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSchedulingService) EXPECT() *MockSchedulingService_Expecter {
	return &MockSchedulingService_Expecter{mock: &_m.Mock}
}

// RetryFailedMatches provides a mock function with given fields: ctx, tournamentID
func (_m *MockSchedulingService) RetryFailedMatches(ctx context.Context, tournamentID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, tournamentID)

	if len(ret) == 0 {
		panic("no return value specified for RetryFailedMatches")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return rf(ctx, tournamentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, tournamentID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tournamentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSchedulingService_RetryFailedMatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetryFailedMatches'
type MockSchedulingService_RetryFailedMatches_Call struct {
	*mock.Call
}

// RetryFailedMatches is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
func (_e *MockSchedulingService_Expecter) RetryFailedMatches(ctx interface{}, tournamentID interface{}) *MockSchedulingService_RetryFailedMatches_Call {
	return &MockSchedulingService_RetryFailedMatches_Call{Call: _e.mock.On("RetryFailedMatches", ctx, tournamentID)}
}

func (_c *MockSchedulingService_RetryFailedMatches_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID)) *MockSchedulingService_RetryFailedMatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSchedulingService_RetryFailedMatches_Call) Return(_a0 int, _a1 error) *MockSchedulingService_RetryFailedMatches_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSchedulingService_RetryFailedMatches_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, error)) *MockSchedulingService_RetryFailedMatches_Call {
	_c.Call.Return(run)
	return _c
}

// RunAllMatches provides a mock function with given fields: ctx, tournamentID
func (_m *MockSchedulingService) RunAllMatches(ctx context.Context, tournamentID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, tournamentID)

	if len(ret) == 0 {
		panic("no return value specified for RunAllMatches")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return rf(ctx, tournamentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, tournamentID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tournamentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSchedulingService_RunAllMatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunAllMatches'
type MockSchedulingService_RunAllMatches_Call struct {
	*mock.Call
}

// RunAllMatches is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
func (_e *MockSchedulingService_Expecter) RunAllMatches(ctx interface{}, tournamentID interface{}) *MockSchedulingService_RunAllMatches_Call {
	return &MockSchedulingService_RunAllMatches_Call{Call: _e.mock.On("RunAllMatches", ctx, tournamentID)}
}

func (_c *MockSchedulingService_RunAllMatches_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID)) *MockSchedulingService_RunAllMatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSchedulingService_RunAllMatches_Call) Return(_a0 int, _a1 error) *MockSchedulingService_RunAllMatches_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSchedulingService_RunAllMatches_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, error)) *MockSchedulingService_RunAllMatches_Call {
	_c.Call.Return(run)
	return _c
}

// RunGameMatches provides a mock function with given fields: ctx, tournamentID, gameType
func (_m *MockSchedulingService) RunGameMatches(ctx context.Context, tournamentID uuid.UUID, gameType string) (int, error) {
	ret := _m.Called(ctx, tournamentID, gameType)

	if len(ret) == 0 {
		panic("no return value specified for RunGameMatches")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (int, error)); ok {
		return rf(ctx, tournamentID, gameType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) int); ok {
		r0 = rf(ctx, tournamentID, gameType)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, tournamentID, gameType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSchedulingService_RunGameMatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunGameMatches'
type MockSchedulingService_RunGameMatches_Call struct {
	*mock.Call
}

// RunGameMatches is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
//   - gameType string
func (_e *MockSchedulingService_Expecter) RunGameMatches(ctx interface{}, tournamentID interface{}, gameType interface{}) *MockSchedulingService_RunGameMatches_Call {
	return &MockSchedulingService_RunGameMatches_Call{Call: _e.mock.On("RunGameMatches", ctx, tournamentID, gameType)}
}

func (_c *MockSchedulingService_RunGameMatches_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID, gameType string)) *MockSchedulingService_RunGameMatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockSchedulingService_RunGameMatches_Call) Return(_a0 int, _a1 error) *MockSchedulingService_RunGameMatches_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSchedulingService_RunGameMatches_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (int, error)) *MockSchedulingService_RunGameMatches_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSchedulingService creates a new instance of MockSchedulingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSchedulingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSchedulingService {
	mock := &MockSchedulingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
