// Code generated by mockery v2.53.6. DO NOT EDIT.

package contractmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockAutoRoundChecker is an autogenerated mock type for the AutoRoundChecker type
type MockAutoRoundChecker struct {
	mock.Mock
}

type MockAutoRoundChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAutoRoundChecker) EXPECT() *MockAutoRoundChecker_Expecter {
	return &MockAutoRoundChecker_Expecter{mock: &_m.Mock}
}

// IsAutoRoundEnabled provides a mock function with given fields: ctx, tournamentID, gameID
func (_m *MockAutoRoundChecker) IsAutoRoundEnabled(ctx context.Context, tournamentID uuid.UUID, gameID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, tournamentID, gameID)

	if len(ret) == 0 {
		panic("no return value specified for IsAutoRoundEnabled")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(ctx, tournamentID, gameID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, tournamentID, gameID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tournamentID, gameID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAutoRoundChecker_IsAutoRoundEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAutoRoundEnabled'
type MockAutoRoundChecker_IsAutoRoundEnabled_Call struct {
	*mock.Call
}

// IsAutoRoundEnabled is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
//   - gameID uuid.UUID
func (_e *MockAutoRoundChecker_Expecter) IsAutoRoundEnabled(ctx interface{}, tournamentID interface{}, gameID interface{}) *MockAutoRoundChecker_IsAutoRoundEnabled_Call {
	return &MockAutoRoundChecker_IsAutoRoundEnabled_Call{Call: _e.mock.On("IsAutoRoundEnabled", ctx, tournamentID, gameID)}
}

func (_c *MockAutoRoundChecker_IsAutoRoundEnabled_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID, gameID uuid.UUID)) *MockAutoRoundChecker_IsAutoRoundEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockAutoRoundChecker_IsAutoRoundEnabled_Call) Return(_a0 bool, _a1 error) *MockAutoRoundChecker_IsAutoRoundEnabled_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAutoRoundChecker_IsAutoRoundEnabled_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (bool, error)) *MockAutoRoundChecker_IsAutoRoundEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAutoRoundChecker creates a new instance of MockAutoRoundChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAutoRoundChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAutoRoundChecker {
	mock := &MockAutoRoundChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
