// Code generated by mockery v2.53.6. DO NOT EDIT.

package contractmocks

import (
	context "context"

	domain "github.com/bmstu-itstech/tjudge/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockGameMatchRepository is an autogenerated mock type for the GameMatchRepository type
type MockGameMatchRepository struct {
	mock.Mock
}

type MockGameMatchRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGameMatchRepository) EXPECT() *MockGameMatchRepository_Expecter {
	return &MockGameMatchRepository_Expecter{mock: &_m.Mock}
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockGameMatchRepository) List(ctx context.Context, filter domain.MatchFilter) ([]*domain.Match, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Match
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.MatchFilter) ([]*domain.Match, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.MatchFilter) []*domain.Match); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Match)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.MatchFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGameMatchRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockGameMatchRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.MatchFilter
func (_e *MockGameMatchRepository_Expecter) List(ctx interface{}, filter interface{}) *MockGameMatchRepository_List_Call {
	return &MockGameMatchRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockGameMatchRepository_List_Call) Run(run func(ctx context.Context, filter domain.MatchFilter)) *MockGameMatchRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.MatchFilter))
	})
	return _c
}

func (_c *MockGameMatchRepository_List_Call) Return(_a0 []*domain.Match, _a1 error) *MockGameMatchRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGameMatchRepository_List_Call) RunAndReturn(run func(context.Context, domain.MatchFilter) ([]*domain.Match, error)) *MockGameMatchRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGameMatchRepository creates a new instance of MockGameMatchRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGameMatchRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGameMatchRepository {
	mock := &MockGameMatchRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
