// Code generated by mockery v2.53.6. DO NOT EDIT.

package contractmocks

import (
	context "context"

	domain "github.com/bmstu-itstech/tjudge/internal/domain"
	game "github.com/bmstu-itstech/tjudge/internal/domain/game"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockGameService is an autogenerated mock type for the GameService type
type MockGameService struct {
	mock.Mock
}

type MockGameService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGameService) EXPECT() *MockGameService_Expecter {
	return &MockGameService_Expecter{mock: &_m.Mock}
}

// AddToTournament provides a mock function with given fields: ctx, tournamentID, gameID
func (_m *MockGameService) AddToTournament(ctx context.Context, tournamentID uuid.UUID, gameID uuid.UUID) error {
	ret := _m.Called(ctx, tournamentID, gameID)

	if len(ret) == 0 {
		panic("no return value specified for AddToTournament")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, tournamentID, gameID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGameService_AddToTournament_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToTournament'
type MockGameService_AddToTournament_Call struct {
	*mock.Call
}

// AddToTournament is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
//   - gameID uuid.UUID
func (_e *MockGameService_Expecter) AddToTournament(ctx interface{}, tournamentID interface{}, gameID interface{}) *MockGameService_AddToTournament_Call {
	return &MockGameService_AddToTournament_Call{Call: _e.mock.On("AddToTournament", ctx, tournamentID, gameID)}
}

func (_c *MockGameService_AddToTournament_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID, gameID uuid.UUID)) *MockGameService_AddToTournament_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockGameService_AddToTournament_Call) Return(_a0 error) *MockGameService_AddToTournament_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGameService_AddToTournament_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockGameService_AddToTournament_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, req
func (_m *MockGameService) Create(ctx context.Context, req *game.CreateRequest) (*domain.Game, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Game
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *game.CreateRequest) (*domain.Game, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *game.CreateRequest) *domain.Game); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Game)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *game.CreateRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGameService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockGameService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req *game.CreateRequest
func (_e *MockGameService_Expecter) Create(ctx interface{}, req interface{}) *MockGameService_Create_Call {
	return &MockGameService_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockGameService_Create_Call) Run(run func(ctx context.Context, req *game.CreateRequest)) *MockGameService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*game.CreateRequest))
	})
	return _c
}

func (_c *MockGameService_Create_Call) Return(_a0 *domain.Game, _a1 error) *MockGameService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGameService_Create_Call) RunAndReturn(run func(context.Context, *game.CreateRequest) (*domain.Game, error)) *MockGameService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockGameService) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGameService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockGameService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockGameService_Expecter) Delete(ctx interface{}, id interface{}) *MockGameService_Delete_Call {
	return &MockGameService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockGameService_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockGameService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGameService_Delete_Call) Return(_a0 error) *MockGameService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGameService_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockGameService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockGameService) GetByID(ctx context.Context, id uuid.UUID) (*domain.Game, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Game
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Game, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Game); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Game)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGameService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockGameService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockGameService_Expecter) GetByID(ctx interface{}, id interface{}) *MockGameService_GetByID_Call {
	return &MockGameService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockGameService_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockGameService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGameService_GetByID_Call) Return(_a0 *domain.Game, _a1 error) *MockGameService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGameService_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Game, error)) *MockGameService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function with given fields: ctx, name
func (_m *MockGameService) GetByName(ctx context.Context, name string) (*domain.Game, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *domain.Game
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Game, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Game); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Game)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGameService_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockGameService_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockGameService_Expecter) GetByName(ctx interface{}, name interface{}) *MockGameService_GetByName_Call {
	return &MockGameService_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockGameService_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockGameService_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGameService_GetByName_Call) Return(_a0 *domain.Game, _a1 error) *MockGameService_GetByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGameService_GetByName_Call) RunAndReturn(run func(context.Context, string) (*domain.Game, error)) *MockGameService_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTournamentID provides a mock function with given fields: ctx, tournamentID
func (_m *MockGameService) GetByTournamentID(ctx context.Context, tournamentID uuid.UUID) ([]*domain.Game, error) {
	ret := _m.Called(ctx, tournamentID)

	if len(ret) == 0 {
		panic("no return value specified for GetByTournamentID")
	}

	var r0 []*domain.Game
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*domain.Game, error)); ok {
		return rf(ctx, tournamentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.Game); ok {
		r0 = rf(ctx, tournamentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Game)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tournamentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGameService_GetByTournamentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTournamentID'
type MockGameService_GetByTournamentID_Call struct {
	*mock.Call
}

// GetByTournamentID is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
func (_e *MockGameService_Expecter) GetByTournamentID(ctx interface{}, tournamentID interface{}) *MockGameService_GetByTournamentID_Call {
	return &MockGameService_GetByTournamentID_Call{Call: _e.mock.On("GetByTournamentID", ctx, tournamentID)}
}

func (_c *MockGameService_GetByTournamentID_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID)) *MockGameService_GetByTournamentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGameService_GetByTournamentID_Call) Return(_a0 []*domain.Game, _a1 error) *MockGameService_GetByTournamentID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGameService_GetByTournamentID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*domain.Game, error)) *MockGameService_GetByTournamentID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockGameService) List(ctx context.Context, filter domain.GameFilter) ([]*domain.Game, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Game
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.GameFilter) ([]*domain.Game, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.GameFilter) []*domain.Game); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Game)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.GameFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGameService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockGameService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.GameFilter
func (_e *MockGameService_Expecter) List(ctx interface{}, filter interface{}) *MockGameService_List_Call {
	return &MockGameService_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockGameService_List_Call) Run(run func(ctx context.Context, filter domain.GameFilter)) *MockGameService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.GameFilter))
	})
	return _c
}

func (_c *MockGameService_List_Call) Return(_a0 []*domain.Game, _a1 error) *MockGameService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGameService_List_Call) RunAndReturn(run func(context.Context, domain.GameFilter) ([]*domain.Game, error)) *MockGameService_List_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveFromTournament provides a mock function with given fields: ctx, tournamentID, gameID
func (_m *MockGameService) RemoveFromTournament(ctx context.Context, tournamentID uuid.UUID, gameID uuid.UUID) error {
	ret := _m.Called(ctx, tournamentID, gameID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFromTournament")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, tournamentID, gameID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGameService_RemoveFromTournament_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveFromTournament'
type MockGameService_RemoveFromTournament_Call struct {
	*mock.Call
}

// RemoveFromTournament is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
//   - gameID uuid.UUID
func (_e *MockGameService_Expecter) RemoveFromTournament(ctx interface{}, tournamentID interface{}, gameID interface{}) *MockGameService_RemoveFromTournament_Call {
	return &MockGameService_RemoveFromTournament_Call{Call: _e.mock.On("RemoveFromTournament", ctx, tournamentID, gameID)}
}

func (_c *MockGameService_RemoveFromTournament_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID, gameID uuid.UUID)) *MockGameService_RemoveFromTournament_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockGameService_RemoveFromTournament_Call) Return(_a0 error) *MockGameService_RemoveFromTournament_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGameService_RemoveFromTournament_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockGameService_RemoveFromTournament_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, req
func (_m *MockGameService) Update(ctx context.Context, id uuid.UUID, req *game.UpdateRequest) (*domain.Game, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Game
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *game.UpdateRequest) (*domain.Game, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *game.UpdateRequest) *domain.Game); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Game)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *game.UpdateRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGameService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockGameService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - req *game.UpdateRequest
func (_e *MockGameService_Expecter) Update(ctx interface{}, id interface{}, req interface{}) *MockGameService_Update_Call {
	return &MockGameService_Update_Call{Call: _e.mock.On("Update", ctx, id, req)}
}

func (_c *MockGameService_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, req *game.UpdateRequest)) *MockGameService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*game.UpdateRequest))
	})
	return _c
}

func (_c *MockGameService_Update_Call) Return(_a0 *domain.Game, _a1 error) *MockGameService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGameService_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, *game.UpdateRequest) (*domain.Game, error)) *MockGameService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGameService creates a new instance of MockGameService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGameService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGameService {
	mock := &MockGameService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
