// Code generated by mockery v2.53.6. DO NOT EDIT.

package contractmocks

import (
	context "context"

	domain "github.com/bmstu-itstech/tjudge/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockGameLeaderboardRepository is an autogenerated mock type for the GameLeaderboardRepository type
type MockGameLeaderboardRepository struct {
	mock.Mock
}

type MockGameLeaderboardRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGameLeaderboardRepository) EXPECT() *MockGameLeaderboardRepository_Expecter {
	return &MockGameLeaderboardRepository_Expecter{mock: &_m.Mock}
}

// GetHeadToHead provides a mock function with given fields: ctx, tournamentID, gameType
func (_m *MockGameLeaderboardRepository) GetHeadToHead(ctx context.Context, tournamentID uuid.UUID, gameType string) ([]*domain.HeadToHeadCell, error) {
	ret := _m.Called(ctx, tournamentID, gameType)

	if len(ret) == 0 {
		panic("no return value specified for GetHeadToHead")
	}

	var r0 []*domain.HeadToHeadCell
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]*domain.HeadToHeadCell, error)); ok {
		return rf(ctx, tournamentID, gameType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []*domain.HeadToHeadCell); ok {
		r0 = rf(ctx, tournamentID, gameType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.HeadToHeadCell)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, tournamentID, gameType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGameLeaderboardRepository_GetHeadToHead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHeadToHead'
type MockGameLeaderboardRepository_GetHeadToHead_Call struct {
	*mock.Call
}

// GetHeadToHead is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
//   - gameType string
func (_e *MockGameLeaderboardRepository_Expecter) GetHeadToHead(ctx interface{}, tournamentID interface{}, gameType interface{}) *MockGameLeaderboardRepository_GetHeadToHead_Call {
	return &MockGameLeaderboardRepository_GetHeadToHead_Call{Call: _e.mock.On("GetHeadToHead", ctx, tournamentID, gameType)}
}

func (_c *MockGameLeaderboardRepository_GetHeadToHead_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID, gameType string)) *MockGameLeaderboardRepository_GetHeadToHead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockGameLeaderboardRepository_GetHeadToHead_Call) Return(_a0 []*domain.HeadToHeadCell, _a1 error) *MockGameLeaderboardRepository_GetHeadToHead_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGameLeaderboardRepository_GetHeadToHead_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) ([]*domain.HeadToHeadCell, error)) *MockGameLeaderboardRepository_GetHeadToHead_Call {
	_c.Call.Return(run)
	return _c
}

// GetLeaderboardByGameType provides a mock function with given fields: ctx, tournamentID, gameType, limit
func (_m *MockGameLeaderboardRepository) GetLeaderboardByGameType(ctx context.Context, tournamentID uuid.UUID, gameType string, limit int) ([]*domain.LeaderboardEntry, error) {
	ret := _m.Called(ctx, tournamentID, gameType, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetLeaderboardByGameType")
	}

	var r0 []*domain.LeaderboardEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int) ([]*domain.LeaderboardEntry, error)); ok {
		return rf(ctx, tournamentID, gameType, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int) []*domain.LeaderboardEntry); ok {
		r0 = rf(ctx, tournamentID, gameType, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.LeaderboardEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, int) error); ok {
		r1 = rf(ctx, tournamentID, gameType, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGameLeaderboardRepository_GetLeaderboardByGameType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLeaderboardByGameType'
type MockGameLeaderboardRepository_GetLeaderboardByGameType_Call struct {
	*mock.Call
}

// GetLeaderboardByGameType is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
//   - gameType string
//   - limit int
func (_e *MockGameLeaderboardRepository_Expecter) GetLeaderboardByGameType(ctx interface{}, tournamentID interface{}, gameType interface{}, limit interface{}) *MockGameLeaderboardRepository_GetLeaderboardByGameType_Call {
	return &MockGameLeaderboardRepository_GetLeaderboardByGameType_Call{Call: _e.mock.On("GetLeaderboardByGameType", ctx, tournamentID, gameType, limit)}
}

func (_c *MockGameLeaderboardRepository_GetLeaderboardByGameType_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID, gameType string, limit int)) *MockGameLeaderboardRepository_GetLeaderboardByGameType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *MockGameLeaderboardRepository_GetLeaderboardByGameType_Call) Return(_a0 []*domain.LeaderboardEntry, _a1 error) *MockGameLeaderboardRepository_GetLeaderboardByGameType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGameLeaderboardRepository_GetLeaderboardByGameType_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, int) ([]*domain.LeaderboardEntry, error)) *MockGameLeaderboardRepository_GetLeaderboardByGameType_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGameLeaderboardRepository creates a new instance of MockGameLeaderboardRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGameLeaderboardRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGameLeaderboardRepository {
	mock := &MockGameLeaderboardRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
