// Code generated by mockery v2.53.6. DO NOT EDIT.

package contractmocks

import (
	context "context"

	domain "github.com/bmstu-itstech/tjudge/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockGameTournamentRepository is an autogenerated mock type for the GameTournamentRepository type
type MockGameTournamentRepository struct {
	mock.Mock
}

type MockGameTournamentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGameTournamentRepository) EXPECT() *MockGameTournamentRepository_Expecter {
	return &MockGameTournamentRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockGameTournamentRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Tournament, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Tournament
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Tournament, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Tournament); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Tournament)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGameTournamentRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockGameTournamentRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockGameTournamentRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockGameTournamentRepository_GetByID_Call {
	return &MockGameTournamentRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockGameTournamentRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockGameTournamentRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGameTournamentRepository_GetByID_Call) Return(_a0 *domain.Tournament, _a1 error) *MockGameTournamentRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGameTournamentRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Tournament, error)) *MockGameTournamentRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGameTournamentRepository creates a new instance of MockGameTournamentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGameTournamentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGameTournamentRepository {
	mock := &MockGameTournamentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
