// Code generated by mockery v2.53.6. DO NOT EDIT.

package contractmocks

import (
	context "context"

	domain "github.com/bmstu-itstech/tjudge/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockTournamentGameStatusRepository is an autogenerated mock type for the TournamentGameStatusRepository type
type MockTournamentGameStatusRepository struct {
	mock.Mock
}

type MockTournamentGameStatusRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTournamentGameStatusRepository) EXPECT() *MockTournamentGameStatusRepository_Expecter {
	return &MockTournamentGameStatusRepository_Expecter{mock: &_m.Mock}
}

// DeactivateAllGames provides a mock function with given fields: ctx, tournamentID
func (_m *MockTournamentGameStatusRepository) DeactivateAllGames(ctx context.Context, tournamentID uuid.UUID) error {
	ret := _m.Called(ctx, tournamentID)

	if len(ret) == 0 {
		panic("no return value specified for DeactivateAllGames")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, tournamentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTournamentGameStatusRepository_DeactivateAllGames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeactivateAllGames'
type MockTournamentGameStatusRepository_DeactivateAllGames_Call struct {
	*mock.Call
}

// DeactivateAllGames is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
func (_e *MockTournamentGameStatusRepository_Expecter) DeactivateAllGames(ctx interface{}, tournamentID interface{}) *MockTournamentGameStatusRepository_DeactivateAllGames_Call {
	return &MockTournamentGameStatusRepository_DeactivateAllGames_Call{Call: _e.mock.On("DeactivateAllGames", ctx, tournamentID)}
}

func (_c *MockTournamentGameStatusRepository_DeactivateAllGames_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID)) *MockTournamentGameStatusRepository_DeactivateAllGames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTournamentGameStatusRepository_DeactivateAllGames_Call) Return(_a0 error) *MockTournamentGameStatusRepository_DeactivateAllGames_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTournamentGameStatusRepository_DeactivateAllGames_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockTournamentGameStatusRepository_DeactivateAllGames_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveGame provides a mock function with given fields: ctx, tournamentID
func (_m *MockTournamentGameStatusRepository) GetActiveGame(ctx context.Context, tournamentID uuid.UUID) (*domain.TournamentGame, error) {
	ret := _m.Called(ctx, tournamentID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveGame")
	}

	var r0 *domain.TournamentGame
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.TournamentGame, error)); ok {
		return rf(ctx, tournamentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.TournamentGame); ok {
		r0 = rf(ctx, tournamentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TournamentGame)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tournamentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTournamentGameStatusRepository_GetActiveGame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveGame'
type MockTournamentGameStatusRepository_GetActiveGame_Call struct {
	*mock.Call
}

// GetActiveGame is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
func (_e *MockTournamentGameStatusRepository_Expecter) GetActiveGame(ctx interface{}, tournamentID interface{}) *MockTournamentGameStatusRepository_GetActiveGame_Call {
	return &MockTournamentGameStatusRepository_GetActiveGame_Call{Call: _e.mock.On("GetActiveGame", ctx, tournamentID)}
}

func (_c *MockTournamentGameStatusRepository_GetActiveGame_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID)) *MockTournamentGameStatusRepository_GetActiveGame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTournamentGameStatusRepository_GetActiveGame_Call) Return(_a0 *domain.TournamentGame, _a1 error) *MockTournamentGameStatusRepository_GetActiveGame_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTournamentGameStatusRepository_GetActiveGame_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.TournamentGame, error)) *MockTournamentGameStatusRepository_GetActiveGame_Call {
	_c.Call.Return(run)
	return _c
}

// GetTournamentGame provides a mock function with given fields: ctx, tournamentID, gameID
func (_m *MockTournamentGameStatusRepository) GetTournamentGame(ctx context.Context, tournamentID uuid.UUID, gameID uuid.UUID) (*domain.TournamentGame, error) {
	ret := _m.Called(ctx, tournamentID, gameID)

	if len(ret) == 0 {
		panic("no return value specified for GetTournamentGame")
	}

	var r0 *domain.TournamentGame
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*domain.TournamentGame, error)); ok {
		return rf(ctx, tournamentID, gameID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *domain.TournamentGame); ok {
		r0 = rf(ctx, tournamentID, gameID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TournamentGame)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tournamentID, gameID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTournamentGameStatusRepository_GetTournamentGame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTournamentGame'
type MockTournamentGameStatusRepository_GetTournamentGame_Call struct {
	*mock.Call
}

// GetTournamentGame is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
//   - gameID uuid.UUID
func (_e *MockTournamentGameStatusRepository_Expecter) GetTournamentGame(ctx interface{}, tournamentID interface{}, gameID interface{}) *MockTournamentGameStatusRepository_GetTournamentGame_Call {
	return &MockTournamentGameStatusRepository_GetTournamentGame_Call{Call: _e.mock.On("GetTournamentGame", ctx, tournamentID, gameID)}
}

func (_c *MockTournamentGameStatusRepository_GetTournamentGame_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID, gameID uuid.UUID)) *MockTournamentGameStatusRepository_GetTournamentGame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockTournamentGameStatusRepository_GetTournamentGame_Call) Return(_a0 *domain.TournamentGame, _a1 error) *MockTournamentGameStatusRepository_GetTournamentGame_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTournamentGameStatusRepository_GetTournamentGame_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*domain.TournamentGame, error)) *MockTournamentGameStatusRepository_GetTournamentGame_Call {
	_c.Call.Return(run)
	return _c
}

// GetTournamentGames provides a mock function with given fields: ctx, tournamentID
func (_m *MockTournamentGameStatusRepository) GetTournamentGames(ctx context.Context, tournamentID uuid.UUID) ([]*domain.TournamentGame, error) {
	ret := _m.Called(ctx, tournamentID)

	if len(ret) == 0 {
		panic("no return value specified for GetTournamentGames")
	}

	var r0 []*domain.TournamentGame
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*domain.TournamentGame, error)); ok {
		return rf(ctx, tournamentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.TournamentGame); ok {
		r0 = rf(ctx, tournamentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.TournamentGame)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tournamentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTournamentGameStatusRepository_GetTournamentGames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTournamentGames'
type MockTournamentGameStatusRepository_GetTournamentGames_Call struct {
	*mock.Call
}

// GetTournamentGames is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
func (_e *MockTournamentGameStatusRepository_Expecter) GetTournamentGames(ctx interface{}, tournamentID interface{}) *MockTournamentGameStatusRepository_GetTournamentGames_Call {
	return &MockTournamentGameStatusRepository_GetTournamentGames_Call{Call: _e.mock.On("GetTournamentGames", ctx, tournamentID)}
}

func (_c *MockTournamentGameStatusRepository_GetTournamentGames_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID)) *MockTournamentGameStatusRepository_GetTournamentGames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTournamentGameStatusRepository_GetTournamentGames_Call) Return(_a0 []*domain.TournamentGame, _a1 error) *MockTournamentGameStatusRepository_GetTournamentGames_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTournamentGameStatusRepository_GetTournamentGames_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*domain.TournamentGame, error)) *MockTournamentGameStatusRepository_GetTournamentGames_Call {
	_c.Call.Return(run)
	return _c
}

// GetTournamentGamesWithDetails provides a mock function with given fields: ctx, tournamentID
func (_m *MockTournamentGameStatusRepository) GetTournamentGamesWithDetails(ctx context.Context, tournamentID uuid.UUID) ([]*domain.TournamentGameWithDetails, error) {
	ret := _m.Called(ctx, tournamentID)

	if len(ret) == 0 {
		panic("no return value specified for GetTournamentGamesWithDetails")
	}

	var r0 []*domain.TournamentGameWithDetails
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*domain.TournamentGameWithDetails, error)); ok {
		return rf(ctx, tournamentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.TournamentGameWithDetails); ok {
		r0 = rf(ctx, tournamentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.TournamentGameWithDetails)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tournamentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTournamentGameStatusRepository_GetTournamentGamesWithDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTournamentGamesWithDetails'
type MockTournamentGameStatusRepository_GetTournamentGamesWithDetails_Call struct {
	*mock.Call
}

// GetTournamentGamesWithDetails is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
func (_e *MockTournamentGameStatusRepository_Expecter) GetTournamentGamesWithDetails(ctx interface{}, tournamentID interface{}) *MockTournamentGameStatusRepository_GetTournamentGamesWithDetails_Call {
	return &MockTournamentGameStatusRepository_GetTournamentGamesWithDetails_Call{Call: _e.mock.On("GetTournamentGamesWithDetails", ctx, tournamentID)}
}

func (_c *MockTournamentGameStatusRepository_GetTournamentGamesWithDetails_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID)) *MockTournamentGameStatusRepository_GetTournamentGamesWithDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTournamentGameStatusRepository_GetTournamentGamesWithDetails_Call) Return(_a0 []*domain.TournamentGameWithDetails, _a1 error) *MockTournamentGameStatusRepository_GetTournamentGamesWithDetails_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTournamentGameStatusRepository_GetTournamentGamesWithDetails_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*domain.TournamentGameWithDetails, error)) *MockTournamentGameStatusRepository_GetTournamentGamesWithDetails_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRoundCompleted provides a mock function with given fields: ctx, tournamentID, gameID
func (_m *MockTournamentGameStatusRepository) MarkRoundCompleted(ctx context.Context, tournamentID uuid.UUID, gameID uuid.UUID) error {
	ret := _m.Called(ctx, tournamentID, gameID)

	if len(ret) == 0 {
		panic("no return value specified for MarkRoundCompleted")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, tournamentID, gameID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTournamentGameStatusRepository_MarkRoundCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRoundCompleted'
type MockTournamentGameStatusRepository_MarkRoundCompleted_Call struct {
	*mock.Call
}

// MarkRoundCompleted is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
//   - gameID uuid.UUID
func (_e *MockTournamentGameStatusRepository_Expecter) MarkRoundCompleted(ctx interface{}, tournamentID interface{}, gameID interface{}) *MockTournamentGameStatusRepository_MarkRoundCompleted_Call {
	return &MockTournamentGameStatusRepository_MarkRoundCompleted_Call{Call: _e.mock.On("MarkRoundCompleted", ctx, tournamentID, gameID)}
}

func (_c *MockTournamentGameStatusRepository_MarkRoundCompleted_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID, gameID uuid.UUID)) *MockTournamentGameStatusRepository_MarkRoundCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockTournamentGameStatusRepository_MarkRoundCompleted_Call) Return(_a0 error) *MockTournamentGameStatusRepository_MarkRoundCompleted_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTournamentGameStatusRepository_MarkRoundCompleted_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockTournamentGameStatusRepository_MarkRoundCompleted_Call {
	_c.Call.Return(run)
	return _c
}

// ResetGameRound provides a mock function with given fields: ctx, tournamentID, gameID
func (_m *MockTournamentGameStatusRepository) ResetGameRound(ctx context.Context, tournamentID uuid.UUID, gameID uuid.UUID) error {
	ret := _m.Called(ctx, tournamentID, gameID)

	if len(ret) == 0 {
		panic("no return value specified for ResetGameRound")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, tournamentID, gameID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTournamentGameStatusRepository_ResetGameRound_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetGameRound'
type MockTournamentGameStatusRepository_ResetGameRound_Call struct {
	*mock.Call
}

// ResetGameRound is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
//   - gameID uuid.UUID
func (_e *MockTournamentGameStatusRepository_Expecter) ResetGameRound(ctx interface{}, tournamentID interface{}, gameID interface{}) *MockTournamentGameStatusRepository_ResetGameRound_Call {
	return &MockTournamentGameStatusRepository_ResetGameRound_Call{Call: _e.mock.On("ResetGameRound", ctx, tournamentID, gameID)}
}

func (_c *MockTournamentGameStatusRepository_ResetGameRound_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID, gameID uuid.UUID)) *MockTournamentGameStatusRepository_ResetGameRound_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockTournamentGameStatusRepository_ResetGameRound_Call) Return(_a0 error) *MockTournamentGameStatusRepository_ResetGameRound_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTournamentGameStatusRepository_ResetGameRound_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockTournamentGameStatusRepository_ResetGameRound_Call {
	_c.Call.Return(run)
	return _c
}

// ResetGameRoundFull provides a mock function with given fields: ctx, tournamentID, gameID, gameType
func (_m *MockTournamentGameStatusRepository) ResetGameRoundFull(ctx context.Context, tournamentID uuid.UUID, gameID uuid.UUID, gameType string) (int64, int64, int64, error) {
	ret := _m.Called(ctx, tournamentID, gameID, gameType)

	if len(ret) == 0 {
		panic("no return value specified for ResetGameRoundFull")
	}

	var r0 int64
	var r1 int64
	var r2 int64
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) (int64, int64, int64, error)); ok {
		return rf(ctx, tournamentID, gameID, gameType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) int64); ok {
		r0 = rf(ctx, tournamentID, gameID, gameType)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string) int64); ok {
		r1 = rf(ctx, tournamentID, gameID, gameType)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, uuid.UUID, string) int64); ok {
		r2 = rf(ctx, tournamentID, gameID, gameType)
	} else {
		r2 = ret.Get(2).(int64)
	}

	if rf, ok := ret.Get(3).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r3 = rf(ctx, tournamentID, gameID, gameType)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockTournamentGameStatusRepository_ResetGameRoundFull_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetGameRoundFull'
type MockTournamentGameStatusRepository_ResetGameRoundFull_Call struct {
	*mock.Call
}

// ResetGameRoundFull is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
//   - gameID uuid.UUID
//   - gameType string
func (_e *MockTournamentGameStatusRepository_Expecter) ResetGameRoundFull(ctx interface{}, tournamentID interface{}, gameID interface{}, gameType interface{}) *MockTournamentGameStatusRepository_ResetGameRoundFull_Call {
	return &MockTournamentGameStatusRepository_ResetGameRoundFull_Call{Call: _e.mock.On("ResetGameRoundFull", ctx, tournamentID, gameID, gameType)}
}

func (_c *MockTournamentGameStatusRepository_ResetGameRoundFull_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID, gameID uuid.UUID, gameType string)) *MockTournamentGameStatusRepository_ResetGameRoundFull_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *MockTournamentGameStatusRepository_ResetGameRoundFull_Call) Return(matchesDeleted int64, participantsReset int64, ratingHistoryDeleted int64, err error) *MockTournamentGameStatusRepository_ResetGameRoundFull_Call {
	_c.Call.Return(matchesDeleted, participantsReset, ratingHistoryDeleted, err)
	return _c
}

func (_c *MockTournamentGameStatusRepository_ResetGameRoundFull_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string) (int64, int64, int64, error)) *MockTournamentGameStatusRepository_ResetGameRoundFull_Call {
	_c.Call.Return(run)
	return _c
}

// SetActiveGame provides a mock function with given fields: ctx, tournamentID, gameID
func (_m *MockTournamentGameStatusRepository) SetActiveGame(ctx context.Context, tournamentID uuid.UUID, gameID uuid.UUID) error {
	ret := _m.Called(ctx, tournamentID, gameID)

	if len(ret) == 0 {
		panic("no return value specified for SetActiveGame")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, tournamentID, gameID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTournamentGameStatusRepository_SetActiveGame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetActiveGame'
type MockTournamentGameStatusRepository_SetActiveGame_Call struct {
	*mock.Call
}

// SetActiveGame is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
//   - gameID uuid.UUID
func (_e *MockTournamentGameStatusRepository_Expecter) SetActiveGame(ctx interface{}, tournamentID interface{}, gameID interface{}) *MockTournamentGameStatusRepository_SetActiveGame_Call {
	return &MockTournamentGameStatusRepository_SetActiveGame_Call{Call: _e.mock.On("SetActiveGame", ctx, tournamentID, gameID)}
}

func (_c *MockTournamentGameStatusRepository_SetActiveGame_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID, gameID uuid.UUID)) *MockTournamentGameStatusRepository_SetActiveGame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockTournamentGameStatusRepository_SetActiveGame_Call) Return(_a0 error) *MockTournamentGameStatusRepository_SetActiveGame_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTournamentGameStatusRepository_SetActiveGame_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockTournamentGameStatusRepository_SetActiveGame_Call {
	_c.Call.Return(run)
	return _c
}

// SetAutoRound provides a mock function with given fields: ctx, tournamentID, gameID, enabled, intervalSecs
func (_m *MockTournamentGameStatusRepository) SetAutoRound(ctx context.Context, tournamentID uuid.UUID, gameID uuid.UUID, enabled bool, intervalSecs int) error {
	ret := _m.Called(ctx, tournamentID, gameID, enabled, intervalSecs)

	if len(ret) == 0 {
		panic("no return value specified for SetAutoRound")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, bool, int) error); ok {
		r0 = rf(ctx, tournamentID, gameID, enabled, intervalSecs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTournamentGameStatusRepository_SetAutoRound_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAutoRound'
type MockTournamentGameStatusRepository_SetAutoRound_Call struct {
	*mock.Call
}

// SetAutoRound is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
//   - gameID uuid.UUID
//   - enabled bool
//   - intervalSecs int
func (_e *MockTournamentGameStatusRepository_Expecter) SetAutoRound(ctx interface{}, tournamentID interface{}, gameID interface{}, enabled interface{}, intervalSecs interface{}) *MockTournamentGameStatusRepository_SetAutoRound_Call {
	return &MockTournamentGameStatusRepository_SetAutoRound_Call{Call: _e.mock.On("SetAutoRound", ctx, tournamentID, gameID, enabled, intervalSecs)}
}

func (_c *MockTournamentGameStatusRepository_SetAutoRound_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID, gameID uuid.UUID, enabled bool, intervalSecs int)) *MockTournamentGameStatusRepository_SetAutoRound_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(bool), args[4].(int))
	})
	return _c
}

func (_c *MockTournamentGameStatusRepository_SetAutoRound_Call) Return(_a0 error) *MockTournamentGameStatusRepository_SetAutoRound_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTournamentGameStatusRepository_SetAutoRound_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, bool, int) error) *MockTournamentGameStatusRepository_SetAutoRound_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTournamentGameStatusRepository creates a new instance of MockTournamentGameStatusRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTournamentGameStatusRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTournamentGameStatusRepository {
	mock := &MockTournamentGameStatusRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
