// Code generated by mockery v2.53.6. DO NOT EDIT.

package contractmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockMatchScheduler is an autogenerated mock type for the MatchScheduler type
type MockMatchScheduler struct {
	mock.Mock
}

type MockMatchScheduler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMatchScheduler) EXPECT() *MockMatchScheduler_Expecter {
	return &MockMatchScheduler_Expecter{mock: &_m.Mock}
}

// ScheduleNewProgramMatches provides a mock function with given fields: ctx, tournamentID, gameID, newProgramID, teamID
func (_m *MockMatchScheduler) ScheduleNewProgramMatches(ctx context.Context, tournamentID uuid.UUID, gameID uuid.UUID, newProgramID uuid.UUID, teamID uuid.UUID) error {
	ret := _m.Called(ctx, tournamentID, gameID, newProgramID, teamID)

	if len(ret) == 0 {
		panic("no return value specified for ScheduleNewProgramMatches")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, tournamentID, gameID, newProgramID, teamID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMatchScheduler_ScheduleNewProgramMatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScheduleNewProgramMatches'
type MockMatchScheduler_ScheduleNewProgramMatches_Call struct {
	*mock.Call
}

// ScheduleNewProgramMatches is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
//   - gameID uuid.UUID
//   - newProgramID uuid.UUID
//   - teamID uuid.UUID
func (_e *MockMatchScheduler_Expecter) ScheduleNewProgramMatches(ctx interface{}, tournamentID interface{}, gameID interface{}, newProgramID interface{}, teamID interface{}) *MockMatchScheduler_ScheduleNewProgramMatches_Call {
	return &MockMatchScheduler_ScheduleNewProgramMatches_Call{Call: _e.mock.On("ScheduleNewProgramMatches", ctx, tournamentID, gameID, newProgramID, teamID)}
}

func (_c *MockMatchScheduler_ScheduleNewProgramMatches_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID, gameID uuid.UUID, newProgramID uuid.UUID, teamID uuid.UUID)) *MockMatchScheduler_ScheduleNewProgramMatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID), args[4].(uuid.UUID))
	})
	return _c
}

func (_c *MockMatchScheduler_ScheduleNewProgramMatches_Call) Return(_a0 error) *MockMatchScheduler_ScheduleNewProgramMatches_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMatchScheduler_ScheduleNewProgramMatches_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, uuid.UUID) error) *MockMatchScheduler_ScheduleNewProgramMatches_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMatchScheduler creates a new instance of MockMatchScheduler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMatchScheduler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMatchScheduler {
	mock := &MockMatchScheduler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
