// Code generated by mockery v2.53.6. DO NOT EDIT.

package contractmocks

import (
	context "context"

	domain "github.com/bmstu-itstech/tjudge/internal/domain"

	mock "github.com/stretchr/testify/mock"

	team "github.com/bmstu-itstech/tjudge/internal/domain/team"

	uuid "github.com/google/uuid"
)

// MockTeamService is an autogenerated mock type for the TeamService type
type MockTeamService struct {
	mock.Mock
}

type MockTeamService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamService) EXPECT() *MockTeamService_Expecter {
	return &MockTeamService_Expecter{mock: &_m.Mock}
}

// CreateTeam provides a mock function with given fields: ctx, req
func (_m *MockTeamService) CreateTeam(ctx context.Context, req *team.CreateTeamRequest) (*domain.Team, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeam")
	}

	var r0 *domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *team.CreateTeamRequest) (*domain.Team, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *team.CreateTeamRequest) *domain.Team); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *team.CreateTeamRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamService_CreateTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTeam'
type MockTeamService_CreateTeam_Call struct {
	*mock.Call
}

// CreateTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - req *team.CreateTeamRequest
func (_e *MockTeamService_Expecter) CreateTeam(ctx interface{}, req interface{}) *MockTeamService_CreateTeam_Call {
	return &MockTeamService_CreateTeam_Call{Call: _e.mock.On("CreateTeam", ctx, req)}
}

func (_c *MockTeamService_CreateTeam_Call) Run(run func(ctx context.Context, req *team.CreateTeamRequest)) *MockTeamService_CreateTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*team.CreateTeamRequest))
	})
	return _c
}

func (_c *MockTeamService_CreateTeam_Call) Return(_a0 *domain.Team, _a1 error) *MockTeamService_CreateTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamService_CreateTeam_Call) RunAndReturn(run func(context.Context, *team.CreateTeamRequest) (*domain.Team, error)) *MockTeamService_CreateTeam_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTeam provides a mock function with given fields: ctx, teamID
func (_m *MockTeamService) DeleteTeam(ctx context.Context, teamID uuid.UUID) error {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTeam")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, teamID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTeamService_DeleteTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTeam'
type MockTeamService_DeleteTeam_Call struct {
	*mock.Call
}

// DeleteTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
func (_e *MockTeamService_Expecter) DeleteTeam(ctx interface{}, teamID interface{}) *MockTeamService_DeleteTeam_Call {
	return &MockTeamService_DeleteTeam_Call{Call: _e.mock.On("DeleteTeam", ctx, teamID)}
}

func (_c *MockTeamService_DeleteTeam_Call) Run(run func(ctx context.Context, teamID uuid.UUID)) *MockTeamService_DeleteTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTeamService_DeleteTeam_Call) Return(_a0 error) *MockTeamService_DeleteTeam_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTeamService_DeleteTeam_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockTeamService_DeleteTeam_Call {
	_c.Call.Return(run)
	return _c
}

// DisqualifyTeam provides a mock function with given fields: ctx, teamID
func (_m *MockTeamService) DisqualifyTeam(ctx context.Context, teamID uuid.UUID) (*team.DisqualifyResult, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for DisqualifyTeam")
	}

	var r0 *team.DisqualifyResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*team.DisqualifyResult, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *team.DisqualifyResult); ok {
		r0 = rf(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*team.DisqualifyResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamService_DisqualifyTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisqualifyTeam'
type MockTeamService_DisqualifyTeam_Call struct {
	*mock.Call
}

// DisqualifyTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
func (_e *MockTeamService_Expecter) DisqualifyTeam(ctx interface{}, teamID interface{}) *MockTeamService_DisqualifyTeam_Call {
	return &MockTeamService_DisqualifyTeam_Call{Call: _e.mock.On("DisqualifyTeam", ctx, teamID)}
}

func (_c *MockTeamService_DisqualifyTeam_Call) Run(run func(ctx context.Context, teamID uuid.UUID)) *MockTeamService_DisqualifyTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTeamService_DisqualifyTeam_Call) Return(_a0 *team.DisqualifyResult, _a1 error) *MockTeamService_DisqualifyTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamService_DisqualifyTeam_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*team.DisqualifyResult, error)) *MockTeamService_DisqualifyTeam_Call {
	_c.Call.Return(run)
	return _c
}

// GetInviteLink provides a mock function with given fields: ctx, teamID, leaderID, baseURL
func (_m *MockTeamService) GetInviteLink(ctx context.Context, teamID uuid.UUID, leaderID uuid.UUID, baseURL string) (string, error) {
	ret := _m.Called(ctx, teamID, leaderID, baseURL)

	if len(ret) == 0 {
		panic("no return value specified for GetInviteLink")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) (string, error)); ok {
		return rf(ctx, teamID, leaderID, baseURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) string); ok {
		r0 = rf(ctx, teamID, leaderID, baseURL)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = rf(ctx, teamID, leaderID, baseURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamService_GetInviteLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInviteLink'
type MockTeamService_GetInviteLink_Call struct {
	*mock.Call
}

// GetInviteLink is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
//   - leaderID uuid.UUID
//   - baseURL string
func (_e *MockTeamService_Expecter) GetInviteLink(ctx interface{}, teamID interface{}, leaderID interface{}, baseURL interface{}) *MockTeamService_GetInviteLink_Call {
	return &MockTeamService_GetInviteLink_Call{Call: _e.mock.On("GetInviteLink", ctx, teamID, leaderID, baseURL)}
}

func (_c *MockTeamService_GetInviteLink_Call) Run(run func(ctx context.Context, teamID uuid.UUID, leaderID uuid.UUID, baseURL string)) *MockTeamService_GetInviteLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *MockTeamService_GetInviteLink_Call) Return(_a0 string, _a1 error) *MockTeamService_GetInviteLink_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamService_GetInviteLink_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string) (string, error)) *MockTeamService_GetInviteLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamByCode provides a mock function with given fields: ctx, code
func (_m *MockTeamService) GetTeamByCode(ctx context.Context, code string) (*domain.Team, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamByCode")
	}

	var r0 *domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Team, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Team); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamService_GetTeamByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamByCode'
type MockTeamService_GetTeamByCode_Call struct {
	*mock.Call
}

// GetTeamByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockTeamService_Expecter) GetTeamByCode(ctx interface{}, code interface{}) *MockTeamService_GetTeamByCode_Call {
	return &MockTeamService_GetTeamByCode_Call{Call: _e.mock.On("GetTeamByCode", ctx, code)}
}

func (_c *MockTeamService_GetTeamByCode_Call) Run(run func(ctx context.Context, code string)) *MockTeamService_GetTeamByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTeamService_GetTeamByCode_Call) Return(_a0 *domain.Team, _a1 error) *MockTeamService_GetTeamByCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamService_GetTeamByCode_Call) RunAndReturn(run func(context.Context, string) (*domain.Team, error)) *MockTeamService_GetTeamByCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamByID provides a mock function with given fields: ctx, id
func (_m *MockTeamService) GetTeamByID(ctx context.Context, id uuid.UUID) (*domain.Team, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamByID")
	}

	var r0 *domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Team, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Team); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamService_GetTeamByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamByID'
type MockTeamService_GetTeamByID_Call struct {
	*mock.Call
}

// GetTeamByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTeamService_Expecter) GetTeamByID(ctx interface{}, id interface{}) *MockTeamService_GetTeamByID_Call {
	return &MockTeamService_GetTeamByID_Call{Call: _e.mock.On("GetTeamByID", ctx, id)}
}

func (_c *MockTeamService_GetTeamByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTeamService_GetTeamByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTeamService_GetTeamByID_Call) Return(_a0 *domain.Team, _a1 error) *MockTeamService_GetTeamByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamService_GetTeamByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Team, error)) *MockTeamService_GetTeamByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamWithMembers provides a mock function with given fields: ctx, teamID
func (_m *MockTeamService) GetTeamWithMembers(ctx context.Context, teamID uuid.UUID) (*domain.TeamWithMembers, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamWithMembers")
	}

	var r0 *domain.TeamWithMembers
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.TeamWithMembers, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.TeamWithMembers); ok {
		r0 = rf(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TeamWithMembers)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamService_GetTeamWithMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamWithMembers'
type MockTeamService_GetTeamWithMembers_Call struct {
	*mock.Call
}

// GetTeamWithMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
func (_e *MockTeamService_Expecter) GetTeamWithMembers(ctx interface{}, teamID interface{}) *MockTeamService_GetTeamWithMembers_Call {
	return &MockTeamService_GetTeamWithMembers_Call{Call: _e.mock.On("GetTeamWithMembers", ctx, teamID)}
}

func (_c *MockTeamService_GetTeamWithMembers_Call) Run(run func(ctx context.Context, teamID uuid.UUID)) *MockTeamService_GetTeamWithMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTeamService_GetTeamWithMembers_Call) Return(_a0 *domain.TeamWithMembers, _a1 error) *MockTeamService_GetTeamWithMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamService_GetTeamWithMembers_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.TeamWithMembers, error)) *MockTeamService_GetTeamWithMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamsByTournament provides a mock function with given fields: ctx, tournamentID
func (_m *MockTeamService) GetTeamsByTournament(ctx context.Context, tournamentID uuid.UUID) ([]*domain.Team, error) {
	ret := _m.Called(ctx, tournamentID)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamsByTournament")
	}

	var r0 []*domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*domain.Team, error)); ok {
		return rf(ctx, tournamentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.Team); ok {
		r0 = rf(ctx, tournamentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tournamentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamService_GetTeamsByTournament_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamsByTournament'
type MockTeamService_GetTeamsByTournament_Call struct {
	*mock.Call
}

// GetTeamsByTournament is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
func (_e *MockTeamService_Expecter) GetTeamsByTournament(ctx interface{}, tournamentID interface{}) *MockTeamService_GetTeamsByTournament_Call {
	return &MockTeamService_GetTeamsByTournament_Call{Call: _e.mock.On("GetTeamsByTournament", ctx, tournamentID)}
}

func (_c *MockTeamService_GetTeamsByTournament_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID)) *MockTeamService_GetTeamsByTournament_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTeamService_GetTeamsByTournament_Call) Return(_a0 []*domain.Team, _a1 error) *MockTeamService_GetTeamsByTournament_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamService_GetTeamsByTournament_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*domain.Team, error)) *MockTeamService_GetTeamsByTournament_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserTeamInTournament provides a mock function with given fields: ctx, tournamentID, userID
func (_m *MockTeamService) GetUserTeamInTournament(ctx context.Context, tournamentID uuid.UUID, userID uuid.UUID) (*domain.Team, error) {
	ret := _m.Called(ctx, tournamentID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserTeamInTournament")
	}

	var r0 *domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*domain.Team, error)); ok {
		return rf(ctx, tournamentID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *domain.Team); ok {
		r0 = rf(ctx, tournamentID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tournamentID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamService_GetUserTeamInTournament_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserTeamInTournament'
type MockTeamService_GetUserTeamInTournament_Call struct {
	*mock.Call
}

// GetUserTeamInTournament is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
//   - userID uuid.UUID
func (_e *MockTeamService_Expecter) GetUserTeamInTournament(ctx interface{}, tournamentID interface{}, userID interface{}) *MockTeamService_GetUserTeamInTournament_Call {
	return &MockTeamService_GetUserTeamInTournament_Call{Call: _e.mock.On("GetUserTeamInTournament", ctx, tournamentID, userID)}
}

func (_c *MockTeamService_GetUserTeamInTournament_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID, userID uuid.UUID)) *MockTeamService_GetUserTeamInTournament_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockTeamService_GetUserTeamInTournament_Call) Return(_a0 *domain.Team, _a1 error) *MockTeamService_GetUserTeamInTournament_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamService_GetUserTeamInTournament_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*domain.Team, error)) *MockTeamService_GetUserTeamInTournament_Call {
	_c.Call.Return(run)
	return _c
}

// JoinTeamByCode provides a mock function with given fields: ctx, req
func (_m *MockTeamService) JoinTeamByCode(ctx context.Context, req *team.JoinTeamRequest) (*domain.Team, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for JoinTeamByCode")
	}

	var r0 *domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *team.JoinTeamRequest) (*domain.Team, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *team.JoinTeamRequest) *domain.Team); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *team.JoinTeamRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamService_JoinTeamByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JoinTeamByCode'
type MockTeamService_JoinTeamByCode_Call struct {
	*mock.Call
}

// JoinTeamByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - req *team.JoinTeamRequest
func (_e *MockTeamService_Expecter) JoinTeamByCode(ctx interface{}, req interface{}) *MockTeamService_JoinTeamByCode_Call {
	return &MockTeamService_JoinTeamByCode_Call{Call: _e.mock.On("JoinTeamByCode", ctx, req)}
}

func (_c *MockTeamService_JoinTeamByCode_Call) Run(run func(ctx context.Context, req *team.JoinTeamRequest)) *MockTeamService_JoinTeamByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*team.JoinTeamRequest))
	})
	return _c
}

func (_c *MockTeamService_JoinTeamByCode_Call) Return(_a0 *domain.Team, _a1 error) *MockTeamService_JoinTeamByCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamService_JoinTeamByCode_Call) RunAndReturn(run func(context.Context, *team.JoinTeamRequest) (*domain.Team, error)) *MockTeamService_JoinTeamByCode_Call {
	_c.Call.Return(run)
	return _c
}

// LeaveTeam provides a mock function with given fields: ctx, teamID, userID
func (_m *MockTeamService) LeaveTeam(ctx context.Context, teamID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, teamID, userID)

	if len(ret) == 0 {
		panic("no return value specified for LeaveTeam")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, teamID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTeamService_LeaveTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LeaveTeam'
type MockTeamService_LeaveTeam_Call struct {
	*mock.Call
}

// LeaveTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
//   - userID uuid.UUID
func (_e *MockTeamService_Expecter) LeaveTeam(ctx interface{}, teamID interface{}, userID interface{}) *MockTeamService_LeaveTeam_Call {
	return &MockTeamService_LeaveTeam_Call{Call: _e.mock.On("LeaveTeam", ctx, teamID, userID)}
}

func (_c *MockTeamService_LeaveTeam_Call) Run(run func(ctx context.Context, teamID uuid.UUID, userID uuid.UUID)) *MockTeamService_LeaveTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockTeamService_LeaveTeam_Call) Return(_a0 error) *MockTeamService_LeaveTeam_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTeamService_LeaveTeam_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockTeamService_LeaveTeam_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMember provides a mock function with given fields: ctx, teamID, memberUserID, leaderID
func (_m *MockTeamService) RemoveMember(ctx context.Context, teamID uuid.UUID, memberUserID uuid.UUID, leaderID uuid.UUID) error {
	ret := _m.Called(ctx, teamID, memberUserID, leaderID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, teamID, memberUserID, leaderID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTeamService_RemoveMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMember'
type MockTeamService_RemoveMember_Call struct {
	*mock.Call
}

// RemoveMember is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
//   - memberUserID uuid.UUID
//   - leaderID uuid.UUID
func (_e *MockTeamService_Expecter) RemoveMember(ctx interface{}, teamID interface{}, memberUserID interface{}, leaderID interface{}) *MockTeamService_RemoveMember_Call {
	return &MockTeamService_RemoveMember_Call{Call: _e.mock.On("RemoveMember", ctx, teamID, memberUserID, leaderID)}
}

func (_c *MockTeamService_RemoveMember_Call) Run(run func(ctx context.Context, teamID uuid.UUID, memberUserID uuid.UUID, leaderID uuid.UUID)) *MockTeamService_RemoveMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockTeamService_RemoveMember_Call) Return(_a0 error) *MockTeamService_RemoveMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTeamService_RemoveMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error) *MockTeamService_RemoveMember_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreTeam provides a mock function with given fields: ctx, teamID
func (_m *MockTeamService) RestoreTeam(ctx context.Context, teamID uuid.UUID) error {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for RestoreTeam")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, teamID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTeamService_RestoreTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreTeam'
type MockTeamService_RestoreTeam_Call struct {
	*mock.Call
}

// RestoreTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
func (_e *MockTeamService_Expecter) RestoreTeam(ctx interface{}, teamID interface{}) *MockTeamService_RestoreTeam_Call {
	return &MockTeamService_RestoreTeam_Call{Call: _e.mock.On("RestoreTeam", ctx, teamID)}
}

func (_c *MockTeamService_RestoreTeam_Call) Run(run func(ctx context.Context, teamID uuid.UUID)) *MockTeamService_RestoreTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTeamService_RestoreTeam_Call) Return(_a0 error) *MockTeamService_RestoreTeam_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTeamService_RestoreTeam_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockTeamService_RestoreTeam_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTeamName provides a mock function with given fields: ctx, teamID, name, leaderID
func (_m *MockTeamService) UpdateTeamName(ctx context.Context, teamID uuid.UUID, name string, leaderID uuid.UUID) (*domain.Team, error) {
	ret := _m.Called(ctx, teamID, name, leaderID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTeamName")
	}

	var r0 *domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, uuid.UUID) (*domain.Team, error)); ok {
		return rf(ctx, teamID, name, leaderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, uuid.UUID) *domain.Team); ok {
		r0 = rf(ctx, teamID, name, leaderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, uuid.UUID) error); ok {
		r1 = rf(ctx, teamID, name, leaderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamService_UpdateTeamName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTeamName'
type MockTeamService_UpdateTeamName_Call struct {
	*mock.Call
}

// UpdateTeamName is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
//   - name string
//   - leaderID uuid.UUID
func (_e *MockTeamService_Expecter) UpdateTeamName(ctx interface{}, teamID interface{}, name interface{}, leaderID interface{}) *MockTeamService_UpdateTeamName_Call {
	return &MockTeamService_UpdateTeamName_Call{Call: _e.mock.On("UpdateTeamName", ctx, teamID, name, leaderID)}
}

func (_c *MockTeamService_UpdateTeamName_Call) Run(run func(ctx context.Context, teamID uuid.UUID, name string, leaderID uuid.UUID)) *MockTeamService_UpdateTeamName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockTeamService_UpdateTeamName_Call) Return(_a0 *domain.Team, _a1 error) *MockTeamService_UpdateTeamName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamService_UpdateTeamName_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, uuid.UUID) (*domain.Team, error)) *MockTeamService_UpdateTeamName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTeamService creates a new instance of MockTeamService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamService {
	mock := &MockTeamService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
