// Code generated by mockery v2.53.6. DO NOT EDIT.

package contractmocks

import (
	context "context"

	auth "github.com/bmstu-itstech/tjudge/internal/domain/auth"

	domain "github.com/bmstu-itstech/tjudge/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockMiddlewareAuthService is an autogenerated mock type for the AuthService type
type MockMiddlewareAuthService struct {
	mock.Mock
}

type MockMiddlewareAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMiddlewareAuthService) EXPECT() *MockMiddlewareAuthService_Expecter {
	return &MockMiddlewareAuthService_Expecter{mock: &_m.Mock}
}

// GetUserFromToken provides a mock function with given fields: ctx, tokenString
func (_m *MockMiddlewareAuthService) GetUserFromToken(ctx context.Context, tokenString string) (*domain.User, error) {
	ret := _m.Called(ctx, tokenString)

	if len(ret) == 0 {
		panic("no return value specified for GetUserFromToken")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(ctx, tokenString)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(ctx, tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMiddlewareAuthService_GetUserFromToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserFromToken'
type MockMiddlewareAuthService_GetUserFromToken_Call struct {
	*mock.Call
}

// GetUserFromToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenString string
func (_e *MockMiddlewareAuthService_Expecter) GetUserFromToken(ctx interface{}, tokenString interface{}) *MockMiddlewareAuthService_GetUserFromToken_Call {
	return &MockMiddlewareAuthService_GetUserFromToken_Call{Call: _e.mock.On("GetUserFromToken", ctx, tokenString)}
}

func (_c *MockMiddlewareAuthService_GetUserFromToken_Call) Run(run func(ctx context.Context, tokenString string)) *MockMiddlewareAuthService_GetUserFromToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMiddlewareAuthService_GetUserFromToken_Call) Return(_a0 *domain.User, _a1 error) *MockMiddlewareAuthService_GetUserFromToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMiddlewareAuthService_GetUserFromToken_Call) RunAndReturn(run func(context.Context, string) (*domain.User, error)) *MockMiddlewareAuthService_GetUserFromToken_Call {
	_c.Call.Return(run)
	return _c
}

// IsTokenBlacklisted provides a mock function with given fields: ctx, token
func (_m *MockMiddlewareAuthService) IsTokenBlacklisted(ctx context.Context, token string) (bool, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for IsTokenBlacklisted")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMiddlewareAuthService_IsTokenBlacklisted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsTokenBlacklisted'
type MockMiddlewareAuthService_IsTokenBlacklisted_Call struct {
	*mock.Call
}

// IsTokenBlacklisted is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockMiddlewareAuthService_Expecter) IsTokenBlacklisted(ctx interface{}, token interface{}) *MockMiddlewareAuthService_IsTokenBlacklisted_Call {
	return &MockMiddlewareAuthService_IsTokenBlacklisted_Call{Call: _e.mock.On("IsTokenBlacklisted", ctx, token)}
}

func (_c *MockMiddlewareAuthService_IsTokenBlacklisted_Call) Run(run func(ctx context.Context, token string)) *MockMiddlewareAuthService_IsTokenBlacklisted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMiddlewareAuthService_IsTokenBlacklisted_Call) Return(_a0 bool, _a1 error) *MockMiddlewareAuthService_IsTokenBlacklisted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMiddlewareAuthService_IsTokenBlacklisted_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockMiddlewareAuthService_IsTokenBlacklisted_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function with given fields: tokenString
func (_m *MockMiddlewareAuthService) ValidateToken(tokenString string) (*auth.Claims, error) {
	ret := _m.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *auth.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*auth.Claims, error)); ok {
		return rf(tokenString)
	}
	if rf, ok := ret.Get(0).(func(string) *auth.Claims); ok {
		r0 = rf(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMiddlewareAuthService_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockMiddlewareAuthService_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - tokenString string
func (_e *MockMiddlewareAuthService_Expecter) ValidateToken(tokenString interface{}) *MockMiddlewareAuthService_ValidateToken_Call {
	return &MockMiddlewareAuthService_ValidateToken_Call{Call: _e.mock.On("ValidateToken", tokenString)}
}

func (_c *MockMiddlewareAuthService_ValidateToken_Call) Run(run func(tokenString string)) *MockMiddlewareAuthService_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockMiddlewareAuthService_ValidateToken_Call) Return(_a0 *auth.Claims, _a1 error) *MockMiddlewareAuthService_ValidateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMiddlewareAuthService_ValidateToken_Call) RunAndReturn(run func(string) (*auth.Claims, error)) *MockMiddlewareAuthService_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMiddlewareAuthService creates a new instance of MockMiddlewareAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMiddlewareAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMiddlewareAuthService {
	mock := &MockMiddlewareAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
