// Code generated by mockery v2.53.6. DO NOT EDIT.

package contractmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockTeamMembershipChecker is an autogenerated mock type for the TeamMembershipChecker type
type MockTeamMembershipChecker struct {
	mock.Mock
}

type MockTeamMembershipChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamMembershipChecker) EXPECT() *MockTeamMembershipChecker_Expecter {
	return &MockTeamMembershipChecker_Expecter{mock: &_m.Mock}
}

// IsTeamDisqualified provides a mock function with given fields: ctx, teamID
func (_m *MockTeamMembershipChecker) IsTeamDisqualified(ctx context.Context, teamID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for IsTeamDisqualified")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = rf(ctx, teamID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamMembershipChecker_IsTeamDisqualified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsTeamDisqualified'
type MockTeamMembershipChecker_IsTeamDisqualified_Call struct {
	*mock.Call
}

// IsTeamDisqualified is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
func (_e *MockTeamMembershipChecker_Expecter) IsTeamDisqualified(ctx interface{}, teamID interface{}) *MockTeamMembershipChecker_IsTeamDisqualified_Call {
	return &MockTeamMembershipChecker_IsTeamDisqualified_Call{Call: _e.mock.On("IsTeamDisqualified", ctx, teamID)}
}

func (_c *MockTeamMembershipChecker_IsTeamDisqualified_Call) Run(run func(ctx context.Context, teamID uuid.UUID)) *MockTeamMembershipChecker_IsTeamDisqualified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTeamMembershipChecker_IsTeamDisqualified_Call) Return(_a0 bool, _a1 error) *MockTeamMembershipChecker_IsTeamDisqualified_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamMembershipChecker_IsTeamDisqualified_Call) RunAndReturn(run func(context.Context, uuid.UUID) (bool, error)) *MockTeamMembershipChecker_IsTeamDisqualified_Call {
	_c.Call.Return(run)
	return _c
}

// IsUserInTeam provides a mock function with given fields: ctx, teamID, userID
func (_m *MockTeamMembershipChecker) IsUserInTeam(ctx context.Context, teamID uuid.UUID, userID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, teamID, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsUserInTeam")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(ctx, teamID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, teamID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, teamID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamMembershipChecker_IsUserInTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsUserInTeam'
type MockTeamMembershipChecker_IsUserInTeam_Call struct {
	*mock.Call
}

// IsUserInTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uuid.UUID
//   - userID uuid.UUID
func (_e *MockTeamMembershipChecker_Expecter) IsUserInTeam(ctx interface{}, teamID interface{}, userID interface{}) *MockTeamMembershipChecker_IsUserInTeam_Call {
	return &MockTeamMembershipChecker_IsUserInTeam_Call{Call: _e.mock.On("IsUserInTeam", ctx, teamID, userID)}
}

func (_c *MockTeamMembershipChecker_IsUserInTeam_Call) Run(run func(ctx context.Context, teamID uuid.UUID, userID uuid.UUID)) *MockTeamMembershipChecker_IsUserInTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockTeamMembershipChecker_IsUserInTeam_Call) Return(_a0 bool, _a1 error) *MockTeamMembershipChecker_IsUserInTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamMembershipChecker_IsUserInTeam_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (bool, error)) *MockTeamMembershipChecker_IsUserInTeam_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTeamMembershipChecker creates a new instance of MockTeamMembershipChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamMembershipChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamMembershipChecker {
	mock := &MockTeamMembershipChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
