// Code generated by mockery v2.53.6. DO NOT EDIT.

package contractmocks

import (
	context "context"

	domain "github.com/bmstu-itstech/tjudge/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockMatchCache is an autogenerated mock type for the MatchCache type
type MockMatchCache struct {
	mock.Mock
}

type MockMatchCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMatchCache) EXPECT() *MockMatchCache_Expecter {
	return &MockMatchCache_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, matchID
func (_m *MockMatchCache) Get(ctx context.Context, matchID uuid.UUID) (*domain.MatchResult, error) {
	ret := _m.Called(ctx, matchID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.MatchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.MatchResult, error)); ok {
		return rf(ctx, matchID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.MatchResult); ok {
		r0 = rf(ctx, matchID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MatchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, matchID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMatchCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockMatchCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - matchID uuid.UUID
func (_e *MockMatchCache_Expecter) Get(ctx interface{}, matchID interface{}) *MockMatchCache_Get_Call {
	return &MockMatchCache_Get_Call{Call: _e.mock.On("Get", ctx, matchID)}
}

func (_c *MockMatchCache_Get_Call) Run(run func(ctx context.Context, matchID uuid.UUID)) *MockMatchCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockMatchCache_Get_Call) Return(_a0 *domain.MatchResult, _a1 error) *MockMatchCache_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMatchCache_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.MatchResult, error)) *MockMatchCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetMatch provides a mock function with given fields: ctx, matchID
func (_m *MockMatchCache) GetMatch(ctx context.Context, matchID uuid.UUID) (*domain.Match, error) {
	ret := _m.Called(ctx, matchID)

	if len(ret) == 0 {
		panic("no return value specified for GetMatch")
	}

	var r0 *domain.Match
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Match, error)); ok {
		return rf(ctx, matchID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Match); ok {
		r0 = rf(ctx, matchID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Match)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, matchID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMatchCache_GetMatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMatch'
type MockMatchCache_GetMatch_Call struct {
	*mock.Call
}

// GetMatch is a helper method to define mock.On call
//   - ctx context.Context
//   - matchID uuid.UUID
func (_e *MockMatchCache_Expecter) GetMatch(ctx interface{}, matchID interface{}) *MockMatchCache_GetMatch_Call {
	return &MockMatchCache_GetMatch_Call{Call: _e.mock.On("GetMatch", ctx, matchID)}
}

func (_c *MockMatchCache_GetMatch_Call) Run(run func(ctx context.Context, matchID uuid.UUID)) *MockMatchCache_GetMatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockMatchCache_GetMatch_Call) Return(_a0 *domain.Match, _a1 error) *MockMatchCache_GetMatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMatchCache_GetMatch_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Match, error)) *MockMatchCache_GetMatch_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, matchID, result
func (_m *MockMatchCache) Set(ctx context.Context, matchID uuid.UUID, result *domain.MatchResult) error {
	ret := _m.Called(ctx, matchID, result)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.MatchResult) error); ok {
		r0 = rf(ctx, matchID, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMatchCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockMatchCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - matchID uuid.UUID
//   - result *domain.MatchResult
func (_e *MockMatchCache_Expecter) Set(ctx interface{}, matchID interface{}, result interface{}) *MockMatchCache_Set_Call {
	return &MockMatchCache_Set_Call{Call: _e.mock.On("Set", ctx, matchID, result)}
}

func (_c *MockMatchCache_Set_Call) Run(run func(ctx context.Context, matchID uuid.UUID, result *domain.MatchResult)) *MockMatchCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*domain.MatchResult))
	})
	return _c
}

func (_c *MockMatchCache_Set_Call) Return(_a0 error) *MockMatchCache_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMatchCache_Set_Call) RunAndReturn(run func(context.Context, uuid.UUID, *domain.MatchResult) error) *MockMatchCache_Set_Call {
	_c.Call.Return(run)
	return _c
}

// SetMatch provides a mock function with given fields: ctx, match
func (_m *MockMatchCache) SetMatch(ctx context.Context, match *domain.Match) error {
	ret := _m.Called(ctx, match)

	if len(ret) == 0 {
		panic("no return value specified for SetMatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Match) error); ok {
		r0 = rf(ctx, match)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMatchCache_SetMatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMatch'
type MockMatchCache_SetMatch_Call struct {
	*mock.Call
}

// SetMatch is a helper method to define mock.On call
//   - ctx context.Context
//   - match *domain.Match
func (_e *MockMatchCache_Expecter) SetMatch(ctx interface{}, match interface{}) *MockMatchCache_SetMatch_Call {
	return &MockMatchCache_SetMatch_Call{Call: _e.mock.On("SetMatch", ctx, match)}
}

func (_c *MockMatchCache_SetMatch_Call) Run(run func(ctx context.Context, match *domain.Match)) *MockMatchCache_SetMatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Match))
	})
	return _c
}

func (_c *MockMatchCache_SetMatch_Call) Return(_a0 error) *MockMatchCache_SetMatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMatchCache_SetMatch_Call) RunAndReturn(run func(context.Context, *domain.Match) error) *MockMatchCache_SetMatch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMatchCache creates a new instance of MockMatchCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMatchCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMatchCache {
	mock := &MockMatchCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
