// Code generated by mockery v2.53.6. DO NOT EDIT.

package contractmocks

import (
	context "context"

	domain "github.com/bmstu-itstech/tjudge/internal/domain"

	mock "github.com/stretchr/testify/mock"

	tournament "github.com/bmstu-itstech/tjudge/internal/domain/tournament"

	uuid "github.com/google/uuid"
)

// MockTournamentService is an autogenerated mock type for the TournamentService type
type MockTournamentService struct {
	mock.Mock
}

type MockTournamentService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTournamentService) EXPECT() *MockTournamentService_Expecter {
	return &MockTournamentService_Expecter{mock: &_m.Mock}
}

// Complete provides a mock function with given fields: ctx, tournamentID
func (_m *MockTournamentService) Complete(ctx context.Context, tournamentID uuid.UUID) error {
	ret := _m.Called(ctx, tournamentID)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, tournamentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTournamentService_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type MockTournamentService_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
func (_e *MockTournamentService_Expecter) Complete(ctx interface{}, tournamentID interface{}) *MockTournamentService_Complete_Call {
	return &MockTournamentService_Complete_Call{Call: _e.mock.On("Complete", ctx, tournamentID)}
}

func (_c *MockTournamentService_Complete_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID)) *MockTournamentService_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTournamentService_Complete_Call) Return(_a0 error) *MockTournamentService_Complete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTournamentService_Complete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockTournamentService_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, req
func (_m *MockTournamentService) Create(ctx context.Context, req *tournament.CreateRequest) (*domain.Tournament, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Tournament
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *tournament.CreateRequest) (*domain.Tournament, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *tournament.CreateRequest) *domain.Tournament); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Tournament)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *tournament.CreateRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTournamentService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTournamentService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req *tournament.CreateRequest
func (_e *MockTournamentService_Expecter) Create(ctx interface{}, req interface{}) *MockTournamentService_Create_Call {
	return &MockTournamentService_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockTournamentService_Create_Call) Run(run func(ctx context.Context, req *tournament.CreateRequest)) *MockTournamentService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*tournament.CreateRequest))
	})
	return _c
}

func (_c *MockTournamentService_Create_Call) Return(_a0 *domain.Tournament, _a1 error) *MockTournamentService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTournamentService_Create_Call) RunAndReturn(run func(context.Context, *tournament.CreateRequest) (*domain.Tournament, error)) *MockTournamentService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMatch provides a mock function with given fields: ctx, tournamentID, program1ID, program2ID, priority
func (_m *MockTournamentService) CreateMatch(ctx context.Context, tournamentID uuid.UUID, program1ID uuid.UUID, program2ID uuid.UUID, priority domain.MatchPriority) (*domain.Match, error) {
	ret := _m.Called(ctx, tournamentID, program1ID, program2ID, priority)

	if len(ret) == 0 {
		panic("no return value specified for CreateMatch")
	}

	var r0 *domain.Match
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, domain.MatchPriority) (*domain.Match, error)); ok {
		return rf(ctx, tournamentID, program1ID, program2ID, priority)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, domain.MatchPriority) *domain.Match); ok {
		r0 = rf(ctx, tournamentID, program1ID, program2ID, priority)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Match)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, domain.MatchPriority) error); ok {
		r1 = rf(ctx, tournamentID, program1ID, program2ID, priority)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTournamentService_CreateMatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMatch'
type MockTournamentService_CreateMatch_Call struct {
	*mock.Call
}

// CreateMatch is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
//   - program1ID uuid.UUID
//   - program2ID uuid.UUID
//   - priority domain.MatchPriority
func (_e *MockTournamentService_Expecter) CreateMatch(ctx interface{}, tournamentID interface{}, program1ID interface{}, program2ID interface{}, priority interface{}) *MockTournamentService_CreateMatch_Call {
	return &MockTournamentService_CreateMatch_Call{Call: _e.mock.On("CreateMatch", ctx, tournamentID, program1ID, program2ID, priority)}
}

func (_c *MockTournamentService_CreateMatch_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID, program1ID uuid.UUID, program2ID uuid.UUID, priority domain.MatchPriority)) *MockTournamentService_CreateMatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID), args[4].(domain.MatchPriority))
	})
	return _c
}

func (_c *MockTournamentService_CreateMatch_Call) Return(_a0 *domain.Match, _a1 error) *MockTournamentService_CreateMatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTournamentService_CreateMatch_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, domain.MatchPriority) (*domain.Match, error)) *MockTournamentService_CreateMatch_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, tournamentID
func (_m *MockTournamentService) Delete(ctx context.Context, tournamentID uuid.UUID) error {
	ret := _m.Called(ctx, tournamentID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, tournamentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTournamentService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTournamentService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
func (_e *MockTournamentService_Expecter) Delete(ctx interface{}, tournamentID interface{}) *MockTournamentService_Delete_Call {
	return &MockTournamentService_Delete_Call{Call: _e.mock.On("Delete", ctx, tournamentID)}
}

func (_c *MockTournamentService_Delete_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID)) *MockTournamentService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTournamentService_Delete_Call) Return(_a0 error) *MockTournamentService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTournamentService_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockTournamentService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockTournamentService) GetByID(ctx context.Context, id uuid.UUID) (*domain.Tournament, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Tournament
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Tournament, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Tournament); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Tournament)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTournamentService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTournamentService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTournamentService_Expecter) GetByID(ctx interface{}, id interface{}) *MockTournamentService_GetByID_Call {
	return &MockTournamentService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockTournamentService_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTournamentService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTournamentService_GetByID_Call) Return(_a0 *domain.Tournament, _a1 error) *MockTournamentService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTournamentService_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Tournament, error)) *MockTournamentService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCrossGameLeaderboard provides a mock function with given fields: ctx, tournamentID
func (_m *MockTournamentService) GetCrossGameLeaderboard(ctx context.Context, tournamentID uuid.UUID) ([]*domain.CrossGameLeaderboardEntry, error) {
	ret := _m.Called(ctx, tournamentID)

	if len(ret) == 0 {
		panic("no return value specified for GetCrossGameLeaderboard")
	}

	var r0 []*domain.CrossGameLeaderboardEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*domain.CrossGameLeaderboardEntry, error)); ok {
		return rf(ctx, tournamentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.CrossGameLeaderboardEntry); ok {
		r0 = rf(ctx, tournamentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.CrossGameLeaderboardEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tournamentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTournamentService_GetCrossGameLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCrossGameLeaderboard'
type MockTournamentService_GetCrossGameLeaderboard_Call struct {
	*mock.Call
}

// GetCrossGameLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
func (_e *MockTournamentService_Expecter) GetCrossGameLeaderboard(ctx interface{}, tournamentID interface{}) *MockTournamentService_GetCrossGameLeaderboard_Call {
	return &MockTournamentService_GetCrossGameLeaderboard_Call{Call: _e.mock.On("GetCrossGameLeaderboard", ctx, tournamentID)}
}

func (_c *MockTournamentService_GetCrossGameLeaderboard_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID)) *MockTournamentService_GetCrossGameLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTournamentService_GetCrossGameLeaderboard_Call) Return(_a0 []*domain.CrossGameLeaderboardEntry, _a1 error) *MockTournamentService_GetCrossGameLeaderboard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTournamentService_GetCrossGameLeaderboard_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*domain.CrossGameLeaderboardEntry, error)) *MockTournamentService_GetCrossGameLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetLeaderboard provides a mock function with given fields: ctx, tournamentID, limit
func (_m *MockTournamentService) GetLeaderboard(ctx context.Context, tournamentID uuid.UUID, limit int) ([]*domain.LeaderboardEntry, error) {
	ret := _m.Called(ctx, tournamentID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetLeaderboard")
	}

	var r0 []*domain.LeaderboardEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) ([]*domain.LeaderboardEntry, error)); ok {
		return rf(ctx, tournamentID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) []*domain.LeaderboardEntry); ok {
		r0 = rf(ctx, tournamentID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.LeaderboardEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = rf(ctx, tournamentID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTournamentService_GetLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLeaderboard'
type MockTournamentService_GetLeaderboard_Call struct {
	*mock.Call
}

// GetLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
//   - limit int
func (_e *MockTournamentService_Expecter) GetLeaderboard(ctx interface{}, tournamentID interface{}, limit interface{}) *MockTournamentService_GetLeaderboard_Call {
	return &MockTournamentService_GetLeaderboard_Call{Call: _e.mock.On("GetLeaderboard", ctx, tournamentID, limit)}
}

func (_c *MockTournamentService_GetLeaderboard_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID, limit int)) *MockTournamentService_GetLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int))
	})
	return _c
}

func (_c *MockTournamentService_GetLeaderboard_Call) Return(_a0 []*domain.LeaderboardEntry, _a1 error) *MockTournamentService_GetLeaderboard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTournamentService_GetLeaderboard_Call) RunAndReturn(run func(context.Context, uuid.UUID, int) ([]*domain.LeaderboardEntry, error)) *MockTournamentService_GetLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetMatches provides a mock function with given fields: ctx, tournamentID, limit, offset
func (_m *MockTournamentService) GetMatches(ctx context.Context, tournamentID uuid.UUID, limit int, offset int) ([]*domain.Match, error) {
	ret := _m.Called(ctx, tournamentID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetMatches")
	}

	var r0 []*domain.Match
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*domain.Match, error)); ok {
		return rf(ctx, tournamentID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*domain.Match); ok {
		r0 = rf(ctx, tournamentID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Match)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, tournamentID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTournamentService_GetMatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMatches'
type MockTournamentService_GetMatches_Call struct {
	*mock.Call
}

// GetMatches is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockTournamentService_Expecter) GetMatches(ctx interface{}, tournamentID interface{}, limit interface{}, offset interface{}) *MockTournamentService_GetMatches_Call {
	return &MockTournamentService_GetMatches_Call{Call: _e.mock.On("GetMatches", ctx, tournamentID, limit, offset)}
}

func (_c *MockTournamentService_GetMatches_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID, limit int, offset int)) *MockTournamentService_GetMatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockTournamentService_GetMatches_Call) Return(_a0 []*domain.Match, _a1 error) *MockTournamentService_GetMatches_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTournamentService_GetMatches_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]*domain.Match, error)) *MockTournamentService_GetMatches_Call {
	_c.Call.Return(run)
	return _c
}

// GetMatchesByRounds provides a mock function with given fields: ctx, tournamentID
func (_m *MockTournamentService) GetMatchesByRounds(ctx context.Context, tournamentID uuid.UUID) ([]*domain.MatchRound, error) {
	ret := _m.Called(ctx, tournamentID)

	if len(ret) == 0 {
		panic("no return value specified for GetMatchesByRounds")
	}

	var r0 []*domain.MatchRound
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*domain.MatchRound, error)); ok {
		return rf(ctx, tournamentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.MatchRound); ok {
		r0 = rf(ctx, tournamentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.MatchRound)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tournamentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTournamentService_GetMatchesByRounds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMatchesByRounds'
type MockTournamentService_GetMatchesByRounds_Call struct {
	*mock.Call
}

// GetMatchesByRounds is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
func (_e *MockTournamentService_Expecter) GetMatchesByRounds(ctx interface{}, tournamentID interface{}) *MockTournamentService_GetMatchesByRounds_Call {
	return &MockTournamentService_GetMatchesByRounds_Call{Call: _e.mock.On("GetMatchesByRounds", ctx, tournamentID)}
}

func (_c *MockTournamentService_GetMatchesByRounds_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID)) *MockTournamentService_GetMatchesByRounds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTournamentService_GetMatchesByRounds_Call) Return(_a0 []*domain.MatchRound, _a1 error) *MockTournamentService_GetMatchesByRounds_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTournamentService_GetMatchesByRounds_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*domain.MatchRound, error)) *MockTournamentService_GetMatchesByRounds_Call {
	_c.Call.Return(run)
	return _c
}

// Join provides a mock function with given fields: ctx, req
func (_m *MockTournamentService) Join(ctx context.Context, req *tournament.JoinRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Join")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *tournament.JoinRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTournamentService_Join_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Join'
type MockTournamentService_Join_Call struct {
	*mock.Call
}

// Join is a helper method to define mock.On call
//   - ctx context.Context
//   - req *tournament.JoinRequest
func (_e *MockTournamentService_Expecter) Join(ctx interface{}, req interface{}) *MockTournamentService_Join_Call {
	return &MockTournamentService_Join_Call{Call: _e.mock.On("Join", ctx, req)}
}

func (_c *MockTournamentService_Join_Call) Run(run func(ctx context.Context, req *tournament.JoinRequest)) *MockTournamentService_Join_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*tournament.JoinRequest))
	})
	return _c
}

func (_c *MockTournamentService_Join_Call) Return(_a0 error) *MockTournamentService_Join_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTournamentService_Join_Call) RunAndReturn(run func(context.Context, *tournament.JoinRequest) error) *MockTournamentService_Join_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockTournamentService) List(ctx context.Context, filter domain.TournamentFilter) ([]*domain.Tournament, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Tournament
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TournamentFilter) ([]*domain.Tournament, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.TournamentFilter) []*domain.Tournament); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Tournament)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.TournamentFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTournamentService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTournamentService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.TournamentFilter
func (_e *MockTournamentService_Expecter) List(ctx interface{}, filter interface{}) *MockTournamentService_List_Call {
	return &MockTournamentService_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockTournamentService_List_Call) Run(run func(ctx context.Context, filter domain.TournamentFilter)) *MockTournamentService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.TournamentFilter))
	})
	return _c
}

func (_c *MockTournamentService_List_Call) Return(_a0 []*domain.Tournament, _a1 error) *MockTournamentService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTournamentService_List_Call) RunAndReturn(run func(context.Context, domain.TournamentFilter) ([]*domain.Tournament, error)) *MockTournamentService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx, tournamentID
func (_m *MockTournamentService) Start(ctx context.Context, tournamentID uuid.UUID) error {
	ret := _m.Called(ctx, tournamentID)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, tournamentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTournamentService_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockTournamentService_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
func (_e *MockTournamentService_Expecter) Start(ctx interface{}, tournamentID interface{}) *MockTournamentService_Start_Call {
	return &MockTournamentService_Start_Call{Call: _e.mock.On("Start", ctx, tournamentID)}
}

func (_c *MockTournamentService_Start_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID)) *MockTournamentService_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTournamentService_Start_Call) Return(_a0 error) *MockTournamentService_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTournamentService_Start_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockTournamentService_Start_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTournamentService creates a new instance of MockTournamentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTournamentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTournamentService {
	mock := &MockTournamentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
