// Code generated by mockery v2.53.6. DO NOT EDIT.

package contractmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockMatchExistenceChecker is an autogenerated mock type for the MatchExistenceChecker type
type MockMatchExistenceChecker struct {
	mock.Mock
}

type MockMatchExistenceChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMatchExistenceChecker) EXPECT() *MockMatchExistenceChecker_Expecter {
	return &MockMatchExistenceChecker_Expecter{mock: &_m.Mock}
}

// GetActiveGameType provides a mock function with given fields: ctx, tournamentID
func (_m *MockMatchExistenceChecker) GetActiveGameType(ctx context.Context, tournamentID uuid.UUID) (string, error) {
	ret := _m.Called(ctx, tournamentID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveGameType")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (string, error)); ok {
		return rf(ctx, tournamentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) string); ok {
		r0 = rf(ctx, tournamentID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tournamentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMatchExistenceChecker_GetActiveGameType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveGameType'
type MockMatchExistenceChecker_GetActiveGameType_Call struct {
	*mock.Call
}

// GetActiveGameType is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
func (_e *MockMatchExistenceChecker_Expecter) GetActiveGameType(ctx interface{}, tournamentID interface{}) *MockMatchExistenceChecker_GetActiveGameType_Call {
	return &MockMatchExistenceChecker_GetActiveGameType_Call{Call: _e.mock.On("GetActiveGameType", ctx, tournamentID)}
}

func (_c *MockMatchExistenceChecker_GetActiveGameType_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID)) *MockMatchExistenceChecker_GetActiveGameType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockMatchExistenceChecker_GetActiveGameType_Call) Return(_a0 string, _a1 error) *MockMatchExistenceChecker_GetActiveGameType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMatchExistenceChecker_GetActiveGameType_Call) RunAndReturn(run func(context.Context, uuid.UUID) (string, error)) *MockMatchExistenceChecker_GetActiveGameType_Call {
	_c.Call.Return(run)
	return _c
}

// HasAnyRunningMatches provides a mock function with given fields: ctx, tournamentID
func (_m *MockMatchExistenceChecker) HasAnyRunningMatches(ctx context.Context, tournamentID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, tournamentID)

	if len(ret) == 0 {
		panic("no return value specified for HasAnyRunningMatches")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return rf(ctx, tournamentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = rf(ctx, tournamentID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tournamentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMatchExistenceChecker_HasAnyRunningMatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasAnyRunningMatches'
type MockMatchExistenceChecker_HasAnyRunningMatches_Call struct {
	*mock.Call
}

// HasAnyRunningMatches is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
func (_e *MockMatchExistenceChecker_Expecter) HasAnyRunningMatches(ctx interface{}, tournamentID interface{}) *MockMatchExistenceChecker_HasAnyRunningMatches_Call {
	return &MockMatchExistenceChecker_HasAnyRunningMatches_Call{Call: _e.mock.On("HasAnyRunningMatches", ctx, tournamentID)}
}

func (_c *MockMatchExistenceChecker_HasAnyRunningMatches_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID)) *MockMatchExistenceChecker_HasAnyRunningMatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockMatchExistenceChecker_HasAnyRunningMatches_Call) Return(_a0 bool, _a1 error) *MockMatchExistenceChecker_HasAnyRunningMatches_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMatchExistenceChecker_HasAnyRunningMatches_Call) RunAndReturn(run func(context.Context, uuid.UUID) (bool, error)) *MockMatchExistenceChecker_HasAnyRunningMatches_Call {
	_c.Call.Return(run)
	return _c
}

// HasStartedMatches provides a mock function with given fields: ctx, tournamentID, gameType
func (_m *MockMatchExistenceChecker) HasStartedMatches(ctx context.Context, tournamentID uuid.UUID, gameType string) (bool, error) {
	ret := _m.Called(ctx, tournamentID, gameType)

	if len(ret) == 0 {
		panic("no return value specified for HasStartedMatches")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (bool, error)); ok {
		return rf(ctx, tournamentID, gameType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) bool); ok {
		r0 = rf(ctx, tournamentID, gameType)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, tournamentID, gameType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMatchExistenceChecker_HasStartedMatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasStartedMatches'
type MockMatchExistenceChecker_HasStartedMatches_Call struct {
	*mock.Call
}

// HasStartedMatches is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID uuid.UUID
//   - gameType string
func (_e *MockMatchExistenceChecker_Expecter) HasStartedMatches(ctx interface{}, tournamentID interface{}, gameType interface{}) *MockMatchExistenceChecker_HasStartedMatches_Call {
	return &MockMatchExistenceChecker_HasStartedMatches_Call{Call: _e.mock.On("HasStartedMatches", ctx, tournamentID, gameType)}
}

func (_c *MockMatchExistenceChecker_HasStartedMatches_Call) Run(run func(ctx context.Context, tournamentID uuid.UUID, gameType string)) *MockMatchExistenceChecker_HasStartedMatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockMatchExistenceChecker_HasStartedMatches_Call) Return(_a0 bool, _a1 error) *MockMatchExistenceChecker_HasStartedMatches_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMatchExistenceChecker_HasStartedMatches_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (bool, error)) *MockMatchExistenceChecker_HasStartedMatches_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMatchExistenceChecker creates a new instance of MockMatchExistenceChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMatchExistenceChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMatchExistenceChecker {
	mock := &MockMatchExistenceChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
