// Code generated by mockery v2.53.6. DO NOT EDIT.

package contractmocks

import (
	context "context"

	domain "github.com/bmstu-itstech/tjudge/internal/domain"
	db "github.com/bmstu-itstech/tjudge/internal/infrastructure/db"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockMatchRepository is an autogenerated mock type for the MatchRepository type
type MockMatchRepository struct {
	mock.Mock
}

type MockMatchRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMatchRepository) EXPECT() *MockMatchRepository_Expecter {
	return &MockMatchRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockMatchRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Match, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Match
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Match, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Match); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Match)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMatchRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockMatchRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockMatchRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockMatchRepository_GetByID_Call {
	return &MockMatchRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockMatchRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockMatchRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockMatchRepository_GetByID_Call) Return(_a0 *domain.Match, _a1 error) *MockMatchRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMatchRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Match, error)) *MockMatchRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDs provides a mock function with given fields: ctx, ids
func (_m *MockMatchRepository) GetByIDs(ctx context.Context, ids []uuid.UUID) ([]*domain.Match, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDs")
	}

	var r0 []*domain.Match
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]*domain.Match, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []*domain.Match); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Match)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMatchRepository_GetByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDs'
type MockMatchRepository_GetByIDs_Call struct {
	*mock.Call
}

// GetByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *MockMatchRepository_Expecter) GetByIDs(ctx interface{}, ids interface{}) *MockMatchRepository_GetByIDs_Call {
	return &MockMatchRepository_GetByIDs_Call{Call: _e.mock.On("GetByIDs", ctx, ids)}
}

func (_c *MockMatchRepository_GetByIDs_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *MockMatchRepository_GetByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *MockMatchRepository_GetByIDs_Call) Return(_a0 []*domain.Match, _a1 error) *MockMatchRepository_GetByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMatchRepository_GetByIDs_Call) RunAndReturn(run func(context.Context, []uuid.UUID) ([]*domain.Match, error)) *MockMatchRepository_GetByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatistics provides a mock function with given fields: ctx, tournamentID
func (_m *MockMatchRepository) GetStatistics(ctx context.Context, tournamentID *uuid.UUID) (*db.MatchStatistics, error) {
	ret := _m.Called(ctx, tournamentID)

	if len(ret) == 0 {
		panic("no return value specified for GetStatistics")
	}

	var r0 *db.MatchStatistics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *uuid.UUID) (*db.MatchStatistics, error)); ok {
		return rf(ctx, tournamentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *uuid.UUID) *db.MatchStatistics); ok {
		r0 = rf(ctx, tournamentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.MatchStatistics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *uuid.UUID) error); ok {
		r1 = rf(ctx, tournamentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMatchRepository_GetStatistics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatistics'
type MockMatchRepository_GetStatistics_Call struct {
	*mock.Call
}

// GetStatistics is a helper method to define mock.On call
//   - ctx context.Context
//   - tournamentID *uuid.UUID
func (_e *MockMatchRepository_Expecter) GetStatistics(ctx interface{}, tournamentID interface{}) *MockMatchRepository_GetStatistics_Call {
	return &MockMatchRepository_GetStatistics_Call{Call: _e.mock.On("GetStatistics", ctx, tournamentID)}
}

func (_c *MockMatchRepository_GetStatistics_Call) Run(run func(ctx context.Context, tournamentID *uuid.UUID)) *MockMatchRepository_GetStatistics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*uuid.UUID))
	})
	return _c
}

func (_c *MockMatchRepository_GetStatistics_Call) Return(_a0 *db.MatchStatistics, _a1 error) *MockMatchRepository_GetStatistics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMatchRepository_GetStatistics_Call) RunAndReturn(run func(context.Context, *uuid.UUID) (*db.MatchStatistics, error)) *MockMatchRepository_GetStatistics_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockMatchRepository) List(ctx context.Context, filter domain.MatchFilter) ([]*domain.Match, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Match
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.MatchFilter) ([]*domain.Match, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.MatchFilter) []*domain.Match); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Match)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.MatchFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMatchRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockMatchRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.MatchFilter
func (_e *MockMatchRepository_Expecter) List(ctx interface{}, filter interface{}) *MockMatchRepository_List_Call {
	return &MockMatchRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockMatchRepository_List_Call) Run(run func(ctx context.Context, filter domain.MatchFilter)) *MockMatchRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.MatchFilter))
	})
	return _c
}

func (_c *MockMatchRepository_List_Call) Return(_a0 []*domain.Match, _a1 error) *MockMatchRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMatchRepository_List_Call) RunAndReturn(run func(context.Context, domain.MatchFilter) ([]*domain.Match, error)) *MockMatchRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMatchRepository creates a new instance of MockMatchRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMatchRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMatchRepository {
	mock := &MockMatchRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
