#!/bin/bash
set -euo pipefail

# Rollback Script for Blue-Green Deployment
# This script rolls back to the previous environment

DEPLOY_DIR="/opt/tjudge"
CURRENT_ENV_FILE="${DEPLOY_DIR}/current_env"
PREVIOUS_ENV_FILE="${DEPLOY_DIR}/previous_env"
NGINX_CONF_DIR="/etc/nginx/conf.d"
ACTIVE_UPSTREAM_CONF="${NGINX_CONF_DIR}/active_upstream.conf"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

get_current_env() {
    if [ -f "$CURRENT_ENV_FILE" ]; then
        cat "$CURRENT_ENV_FILE"
    else
        echo "blue"
    fi
}

get_previous_env() {
    local current=$(get_current_env)
    if [ "$current" == "blue" ]; then
        echo "green"
    else
        echo "blue"
    fi
}

# Update nginx upstream configuration
update_nginx_upstream() {
    local target_env=$1

    log_info "Rolling back nginx upstream to ${target_env}..."

    cat > "${ACTIVE_UPSTREAM_CONF}" <<EOF
# Active upstream configuration
# Generated by rollback.sh at $(date)
# Rolled back to: ${target_env}

upstream api_active {
    server tjudge-api-${target_env}:8080;
    keepalive 32;
}
EOF

    log_success "Nginx upstream configuration rolled back"
}

# Reload nginx
reload_nginx() {
    log_info "Reloading nginx..."

    if ! nginx -t 2>/dev/null; then
        log_error "Nginx configuration test failed"
        return 1
    fi

    if docker exec tjudge-nginx nginx -s reload 2>/dev/null; then
        log_success "Nginx reloaded successfully"
    elif systemctl reload nginx 2>/dev/null; then
        log_success "Nginx reloaded successfully (systemctl)"
    else
        nginx -s reload
        log_success "Nginx reloaded successfully (direct)"
    fi
}

# Verify target environment is healthy
verify_health() {
    local target_env=$1
    local max_attempts=30
    local attempt=1

    log_info "Verifying ${target_env} is healthy..."

    while [ $attempt -le $max_attempts ]; do
        if docker inspect --format='{{.State.Health.Status}}' "tjudge-api-${target_env}" 2>/dev/null | grep -q "healthy"; then
            log_success "${target_env} is healthy"
            return 0
        fi
        echo -n "."
        sleep 2
        attempt=$((attempt + 1))
    done

    log_error "${target_env} is not healthy"
    return 1
}

# Save the current environment
save_current_env() {
    local target_env=$1
    echo "$target_env" > "$CURRENT_ENV_FILE"
    log_success "Current environment updated to ${target_env}"
}

# Main
main() {
    local current_env=$(get_current_env)
    local previous_env=$(get_previous_env)

    log_info "=== Rollback ==="
    log_info "Current active: ${current_env}"
    log_info "Rolling back to: ${previous_env}"
    echo ""

    # Verify previous environment is still running and healthy
    if ! verify_health "$previous_env"; then
        log_error "Cannot rollback: ${previous_env} is not running or not healthy"
        log_info "Try starting it first with: docker-compose -f deployments/blue-green/docker-compose.${previous_env}.yml up -d"
        exit 1
    fi

    # Confirm rollback
    read -p "Are you sure you want to rollback to ${previous_env}? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        log_info "Rollback cancelled"
        exit 0
    fi

    # Update nginx configuration
    update_nginx_upstream "$previous_env"

    # Reload nginx
    reload_nginx

    # Wait for connections to drain
    log_info "Waiting for connections to drain..."
    sleep 5

    # Save the current environment
    save_current_env "$previous_env"

    log_success "=== Rollback to ${previous_env} complete ==="
    log_warning "The failed deployment (${current_env}) is still running"
    log_info "You may want to stop it after investigation:"
    log_info "docker-compose -f deployments/blue-green/docker-compose.${current_env}.yml down"
}

main "$@"
