#!/bin/bash
set -euo pipefail

# Traffic Switch Script for Blue-Green Deployment
# This script switches nginx to route traffic to the new environment

DEPLOY_DIR="/opt/tjudge"
CURRENT_ENV_FILE="${DEPLOY_DIR}/current_env"
NGINX_CONF_DIR="/etc/nginx/conf.d"
ACTIVE_UPSTREAM_CONF="${NGINX_CONF_DIR}/active_upstream.conf"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

get_current_env() {
    if [ -f "$CURRENT_ENV_FILE" ]; then
        cat "$CURRENT_ENV_FILE"
    else
        echo "blue"
    fi
}

get_inactive_env() {
    local current=$(get_current_env)
    if [ "$current" == "blue" ]; then
        echo "green"
    else
        echo "blue"
    fi
}

# Update nginx upstream configuration
update_nginx_upstream() {
    local target_env=$1

    log_info "Updating nginx upstream to ${target_env}..."

    # Create the active upstream configuration
    cat > "${ACTIVE_UPSTREAM_CONF}" <<EOF
# Active upstream configuration
# Generated by switch-traffic.sh at $(date)
# Active environment: ${target_env}

upstream api_active {
    server tjudge-api-${target_env}:8080;
    keepalive 32;
}
EOF

    log_success "Nginx upstream configuration updated"
}

# Reload nginx
reload_nginx() {
    log_info "Reloading nginx..."

    # Test nginx configuration
    if ! nginx -t 2>/dev/null; then
        log_error "Nginx configuration test failed"
        return 1
    fi

    # Reload nginx
    if docker exec tjudge-nginx nginx -s reload 2>/dev/null; then
        log_success "Nginx reloaded successfully"
    elif systemctl reload nginx 2>/dev/null; then
        log_success "Nginx reloaded successfully (systemctl)"
    else
        nginx -s reload
        log_success "Nginx reloaded successfully (direct)"
    fi
}

# Verify traffic is going to the new environment
verify_traffic() {
    local target_env=$1

    log_info "Verifying traffic routing..."

    # Make a few requests and check if they go to the right environment
    local success_count=0
    local total=5

    for i in $(seq 1 $total); do
        local response=$(curl -s "http://localhost/health" 2>/dev/null || echo "")
        if echo "$response" | grep -q "healthy\|ok"; then
            success_count=$((success_count + 1))
        fi
        sleep 1
    done

    if [ $success_count -ge $((total - 1)) ]; then
        log_success "Traffic verification passed (${success_count}/${total} successful)"
        return 0
    else
        log_error "Traffic verification failed (${success_count}/${total} successful)"
        return 1
    fi
}

# Update the current environment file
save_current_env() {
    local target_env=$1
    echo "$target_env" > "$CURRENT_ENV_FILE"
    log_success "Current environment updated to ${target_env}"
}

# Main
main() {
    local current_env=$(get_current_env)
    local target_env=$(get_inactive_env)

    log_info "=== Traffic Switch ==="
    log_info "Current active: ${current_env}"
    log_info "Switching to: ${target_env}"
    echo ""

    # Verify target environment is healthy before switching
    log_info "Verifying ${target_env} is healthy..."
    if ! docker inspect --format='{{.State.Health.Status}}' "tjudge-api-${target_env}" 2>/dev/null | grep -q "healthy"; then
        log_error "${target_env} environment is not healthy. Aborting switch."
        exit 1
    fi
    log_success "${target_env} is healthy"

    # Update nginx configuration
    update_nginx_upstream "$target_env"

    # Reload nginx
    reload_nginx

    # Wait a moment for connections to drain
    log_info "Waiting for connections to drain..."
    sleep 5

    # Verify traffic
    if ! verify_traffic "$target_env"; then
        log_error "Traffic verification failed. Consider rolling back."
        exit 1
    fi

    # Save the new current environment
    save_current_env "$target_env"

    log_success "=== Traffic successfully switched to ${target_env} ==="
    log_info "Previous environment (${current_env}) is still running"
    log_info "Run 'docker-compose -f deployments/blue-green/docker-compose.${current_env}.yml down' to stop it"
}

main "$@"
